ResTable = {
    ["langTable"] = {
        "CHN",
        "POL",
        "ENG",
    },
    ["langInfoTable"] = {
        ["CHN"] = "中文简体",
        ["POL"] = "POLSKI",
        ["ENG"] = "ENGLISH",
    },
    ["szModule"] = "Interpolate",
    ["nVersion"] = "1.00",
["strTable"] = {

    [L"..\\NandFlash\\Documents and Settings\\矩形铣底.nc"] = {
                   [L"CHN"] = L"..\\NandFlash\\Documents and Settings\\矩形铣底.nc",
                   [L"POL"] = L"..\\NandFlash\\Documents and Settings\\RectMill.nc",
                   [L"ENG"] = L"..\\NandFlash\\Documents and Settings\\RectMill.nc",},

    [L"G59 工件偏置"] = {
                   [L"CHN"] = L"G59 工件偏置",
                   [L"POL"] = L"Odsuniecie G59",
                   [L"ENG"] = L"G59 Offset",},

    [L"* 手动是否受进给倍率影响"] = {
                   [L"CHN"] = L"* 手动是否受进给倍率影响",
                   [L"POL"] = L"* Stopien w trybie recznym",
                   [L"ENG"] = L"* Ratio OnIn MANU Mode",},

    [L"1.抬刀高度"] = {
                   [L"CHN"] = L"1.抬刀高度",
                   [L"POL"] = L"1.Wys. Podnoszenia",
                   [L"ENG"] = L"1.Lifting Height",},

    [L"* 空行程移动时抬刀高度"] = {
                   [L"CHN"] = L"* 空行程移动时抬刀高度",
                   [L"POL"] = L"* Wysokosc podniesienia przy G00",
                   [L"ENG"] = L"* Lifting Height At G00",},

    [L"微调"] = {
                   [L"CHN"] = L"微调",
                   [L"POL"] = L"Jigg",
                   [L"ENG"] = L"Jigg",},

    [L"* 开启换刀提示"] = {
                   [L"CHN"] = L"* 开启换刀提示",
                   [L"POL"] = L"* Wlacz Wskaz. Wym. Narz.",
                   [L"ENG"] = L"* Enable  Tool Change Tip",},

    [L"9.刀具位置"] = {
                   [L"CHN"] = L"9.刀具位置",
                   [L"POL"] = L"9.Pozycja Narz",
                   [L"ENG"] = L"9.Tool position",},

    [L"* 退刀量"] = {
                   [L"CHN"] = L"* 退刀量",
                   [L"POL"] = L"* Wartosc Odsuniecia",
                   [L"ENG"] = L"* Retract Amount",},

    [L"* 使用选刀加工"] = {
                   [L"CHN"] = L"* 使用选刀加工",
                   [L"POL"] = L"* Liczba proc. na narz.",
                   [L"ENG"] = L"* Process Per Tool No.",},

    [L"行间距"] = {
                   [L"CHN"] = L"行间距",
                   [L"POL"] = L"Odstep Wierszy",
                   [L"ENG"] = L"RowSpace",},

    [L"%d:%d:%d"] = {
                   [L"CHN"] = L"%d:%d:%d",
                   [L"POL"] = L"%d:%d:%d",
                   [L"ENG"] = L"%d:%d:%d",},

    [L"4.开启换刀提示"] = {
                   [L"CHN"] = L"4.开启换刀提示",
                   [L"POL"] = L"4.Wskaz. Wym. Narz.",
                   [L"ENG"] = L"4.ToolChangeTip",},

    [L"6.换刀上位"] = {
                   [L"CHN"] = L"6.换刀上位",
                   [L"POL"] = L"6.Poz Wycin.",
                   [L"ENG"] = L"6.Cut Up Pos",},

    [L"5.退刀量"] = {
                   [L"CHN"] = L"5.退刀量",
                   [L"POL"] = L"5.Wartosc Odsuniecia",
                   [L"ENG"] = L"5.Retract Amount",},

    [L"3.对刀块Z 坐标"] = {
                   [L"CHN"] = L"3.对刀块Z 坐标",
                   [L"POL"] = L"3.Wsp. Kalibr. Z",
                   [L"ENG"] = L"3.Z Cali Coor",},

    [L"X-:"] = {
                   [L"CHN"] = L"X-:",
                   [L"POL"] = L"Y-:", "Z-:",
                   [L"ENG"] = L"Y-:", "Z-:",},

    [L"3.插入模式"] = {
                   [L"CHN"] = L"3.插入模式",
                   [L"POL"] = L"3.Wstawianie",
                   [L"ENG"] = L"3.Insert Type",},

    [L"%d. 刀补号%d"] = {
                   [L"CHN"] = L"%d. 刀补号%d",
                   [L"POL"] = L"%d.Narz.%d",
                   [L"ENG"] = L"%d.Tool%d",},

    [L"3.刀具长度"] = {
                   [L"CHN"] = L"3.刀具长度",
                   [L"POL"] = L"3.Dlugosc Narzedzia",
                   [L"ENG"] = L"3.Tool Length",},

    [L"减速距离"] = {
                   [L"CHN"] = L"减速距离",
                   [L"POL"] = L" Odleglosc Zwalniania",
                   [L"ENG"] = L"  Decel.  Distance",},

    [L"暂停"] = {
                   [L"CHN"] = L"暂停",
                   [L"POL"] = L"Pauza",
                   [L"ENG"] = L"Paus",},

    [L"* 形状独立加工"] = {
                   [L"CHN"] = L"* 形状独立加工",
                   [L"POL"] = L"* Przetwarzaj ksztalty osobno",
                   [L"ENG"] = L"* Process shape separately",},

    [L"3.脉冲当量"] = {
                   [L"CHN"] = L"3.脉冲当量",
                   [L"POL"] = L"3.Impulsy",
                   [L"ENG"] = L"3.Pulse Equiv.",},

    [L"速度"] = {
                   [L"CHN"] = L"速度",
                   [L"POL"] = L"Predkosc",
                   [L"ENG"] = L"Speed",},

    [L"5.对刀块坐标"] = {
                   [L"CHN"] = L"5.对刀块坐标",
                   [L"POL"] = L"5.Wspolrzedne Kalibr.",
                   [L"ENG"] = L"5.Cali Coor",},

    [L"6.选择坐标系"] = {
                   [L"CHN"] = L"6.选择坐标系",
                   [L"POL"] = L"6.Wybierz WCS",
                   [L"ENG"] = L"6.Select WCS",},

    [L"4.旋转工件半径"] = {
                   [L"CHN"] = L"4.旋转工件半径",
                   [L"POL"] = L"4.Promien obr.",
                   [L"ENG"] = L"4.Rev.WorkRadius",},

    [L"2.工件偏置"] = {
                   [L"CHN"] = L"2.工件偏置",
                   [L"POL"] = L"2.Odsuniecie robocze",
                   [L"ENG"] = L"2.Work Offset",},

    [L"2.求交模式"] = {
                   [L"CHN"] = L"2.求交模式",
                   [L"POL"] = L"2.Przecinanie",
                   [L"ENG"] = L"2.Intersect Type",},

    [L"Y:"] = {
                   [L"CHN"] = L"Y:",
                   [L"POL"] = L"Y:",
                   [L"ENG"] = L"Y:",},

    [L"旋转轴最大速度"] = {
                   [L"CHN"] = L"旋转轴最大速度",
                   [L"POL"] = L"Maks. Predk. Katowa Obr. Y",
                   [L"ENG"] = L"Max. Vel. Of Rotary Y",},

    [L"9.对刀仪厚度"] = {
                   [L"CHN"] = L"9.对刀仪厚度",
                   [L"POL"] = L"9.Grubosc Plytki Kalibr.",
                   [L"ENG"] = L"9.CalibThickness",},

    [L"10. S 型算法"] = {
                   [L"CHN"] = L"10. S 型算法",
                   [L"POL"] = L"10 Wlacz Algorytm S",
                   [L"ENG"] = L"10Enable S Algo",},

    [L"加工文件内容为空!"] = {
                   [L"CHN"] = L"加工文件内容为空!",
                   [L"POL"] = L"Pusty plik!",
                   [L"ENG"] = L"Empty file!",},

    [L"15. 润滑设置"] = {
                   [L"CHN"] = L"15. 润滑设置",
                   [L"POL"] = L"15Smarowanie",
                   [L"ENG"] = L"15Lube",},

    [L"1.对刀块X 坐标"] = {
                   [L"CHN"] = L"1.对刀块X 坐标",
                   [L"POL"] = L"1.Wspolrzedne kalibr. X",
                   [L"ENG"] = L"1.X Cali Coor",},

    [L"两次启用润滑功能的间隔时间"] = {
                   [L"CHN"] = L"两次启用润滑功能的间隔时间",
                   [L"POL"] = L" Odstep miedzy smarowaniami",
                   [L"ENG"] = L" Interval Between Two Lubes",},

    [L"3.键盘按键诊断"] = {
                   [L"CHN"] = L"3.键盘按键诊断",
                   [L"POL"] = L"3.Diagnostyka Klawiszy",
                   [L"ENG"] = L"3.Keypress Diag",},

    [L"1.备份参数"] = {
                   [L"CHN"] = L"1.备份参数",
                   [L"POL"] = L"1.Parametry Kopii",
                   [L"ENG"] = L"1.Backup Params",},

    [L"17. 轨迹平滑时间"] = {
                   [L"CHN"] = L"17. 轨迹平滑时间",
                   [L"POL"] = L"17 Czas wygladzania",
                   [L"ENG"] = L"17Smoothing Time",},

    [L"参数保存成功!"] = {
                   [L"CHN"] = L"参数保存成功!",
                   [L"POL"] = L"Pomyslnie zapisano!",
                   [L"ENG"] = L"SuccessfullySaved!",},

    [L"未找到参数备份文件!"] = {
                   [L"CHN"] = L"未找到参数备份文件!",
                   [L"POL"] = L"Kopia Zapasowa nie odnaleziona!",
                   [L"ENG"] = L"Backup File Not Found!",},

    [L"是否立即重启?"] = {
                   [L"CHN"] = L"是否立即重启?",
                   [L"POL"] = L"Zrestartowac natychmiast?",
                   [L"ENG"] = L"Reboot      Immediately?",},

    [L"参数恢复失败!"] = {
                   [L"CHN"] = L"参数恢复失败!",
                   [L"POL"] = L" Nieudane przywrocenie!",
                   [L"ENG"] = L" Restore      Failed!",},

    [L"步XY"] = {
                   [L"CHN"] = L"步XY",
                   [L"POL"] = L"Krok XY",
                   [L"ENG"] = L"StepXY",},

    [L"* 旋转轴脉冲当量"] = {
                   [L"CHN"] = L"* 旋转轴脉冲当量",
                   [L"POL"] = L"* Impulsy osi obrotowej Y",
                   [L"ENG"] = L"* Rotary YPulse Equivalent",},

    [L"2.加工速度"] = {
                   [L"CHN"] = L"2.加工速度",
                   [L"POL"] = L"2.Predkosc Gxx",
                   [L"ENG"] = L"2.Gxx Speed",},

    [L"按[OK]选择坐标系"] = {
                   [L"CHN"] = L"按[OK]选择坐标系",
                   [L"POL"] = L"Wybierz przez [OK]",
                   [L"ENG"] = L"Select by[OK]key",},

    [L"文件解析中。。。"] = {
                   [L"CHN"] = L"文件解析中。。。",
                   [L"POL"] = L"Interpreter",
                   [L"ENG"] = L"Parsing",},

    [L"请输入注册码"] = {
                   [L"CHN"] = L"请输入注册码",
                   [L"POL"] = L"Wprowadz kod Rejestracyjny",
                   [L"ENG"] = L"Enter Reg. Code",},

    [L":切换至上或下一个字母\nOK: 若输入框未写满, 输入当前选中字母; 否则使用当前输入框内数据注册\nESC:返回"] = {
                   [L"CHN"] = L":切换至上或下一个字母\nOK: 若输入框未写满, 输入当前选中字母; 否则使用当前输入框内数据注册\nESC:返回",
                   [L"POL"] = L":przesun do ostatniego/nastepnego znaku\n[OK]:OK: wprowadz aktualnie wybrany znak do okna gdzie kod nie jest kompletny lub zarejestruj z kodem\n[ESC]:Wyjdz\n\
\nAbbreviation: Reg.:Register",
                   [L"ENG"] = L":shift tothe last/next letter\n[OK]:OK: inputthe currently selected lett-er into the   input box whenthe code isn'tcomplete, or  register with the current   code\n[ESC]:Quit\n\
\nAbbreviation: Reg.:Register",},

    [L"未找到参数文件!"] = {
                   [L"CHN"] = L"未找到参数文件!",
                   [L"POL"] = L"Plik Parametrow nie znaleziony!",
                   [L"ENG"] = L"Param File  Not Found!",},

    [L"不能加载多个文件!"] = {
                   [L"CHN"] = L"不能加载多个文件!",
                   [L"POL"] = L"Nieudana proba zaladowania wielu plikow!",
                   [L"ENG"] = L"Unable To Ld Multi-file!",},

    [L"永久使用"] = {
                   [L"CHN"] = L"永久使用",
                   [L"POL"] = L"Bezgraniczne",
                   [L"ENG"] = L"Limitless",},

    [L"8.删除日志"] = {
                   [L"CHN"] = L"8.删除日志",
                   [L"POL"] = L"8.Usuwanie pliku dziennika",
                   [L"ENG"] = L"8.Delete Log",},

    [L"9.磁盘剩余空间"] = {
                   [L"CHN"] = L"9.磁盘剩余空间",
                   [L"POL"] = L"9.Przestrzen dyskowa",
                   [L"ENG"] = L"9.Disk Space",},

    [L"确定开始断点继续？"] = {
                   [L"CHN"] = L"确定开始断点继续？",
                   [L"POL"] = L"Powrocic do punktu przerwania?",
                   [L"ENG"] = L"OK to start breakpoint  resuming?",},

    [L"2.刀补类型"] = {
                   [L"CHN"] = L"2.刀补类型",
                   [L"POL"] = L"2.Typ Kompensacji Narzedzia",
                   [L"ENG"] = L"2.ToolCompType",},

    [L"语言选择失败！"] = {
                   [L"CHN"] = L"语言选择失败！",
                   [L"POL"] = L"Nieudana proba przelaczenia!",
                   [L"ENG"] = L"Failed To   Switch!",},

    [L"没有检测到U 盘!"] = {
                   [L"CHN"] = L"没有检测到U 盘!",
                   [L"POL"] = L" Dysk USB nie zostal odnaleziony!",
                   [L"ENG"] = L" U-disk Is   Not Found!",},

    [L"存在日志文件，是否覆盖?"] = {
                   [L"CHN"] = L"存在日志文件，是否覆盖?",
                   [L"POL"] = L"Czy zastapic obecny plik dziennika?",
                   [L"ENG"] = L"Overwrite   Existed Log?",},

    [L"2.导出日志"] = {
                   [L"CHN"] = L"2.导出日志",
                   [L"POL"] = L"2.Eksportowanie dziennika",
                   [L"ENG"] = L"2.Export Log",},

    [L"描述：帮助弹出延时"] = {
                   [L"CHN"] = L"描述：帮助弹出延时",
                   [L"POL"] = L"Opoznienie wyswietlania pomocy",
                   [L"ENG"] = L"Spec.:Help Messa-ge Show Delay",},

    [L"4.注册"] = {
                   [L"CHN"] = L"4.注册",
                   [L"POL"] = L"4.Rejestracja",
                   [L"ENG"] = L"4.Register",},

    [L"6.重启"] = {
                   [L"CHN"] = L"6.重启",
                   [L"POL"] = L"6.Restart",
                   [L"ENG"] = L"6.Reboot",},

    [L"是否循环加工"] = {
                   [L"CHN"] = L"是否循环加工",
                   [L"POL"] = L"Wlacz Cykl Przetwarzania",
                   [L"ENG"] = L"Enable    Cycle Process",},

    [L"7.退出系统"] = {
                   [L"CHN"] = L"7.退出系统",
                   [L"POL"] = L"7.Wyjscie",
                   [L"ENG"] = L"7.Exit",},

    [L"加载文件失败!"] = {
                   [L"CHN"] = L"加载文件失败!",
                   [L"POL"] = L"Nieudana proba wczytania pliku!",
                   [L"ENG"] = L"Failed To   Load File!",},

    [L"7.换刀移动速度"] = {
                   [L"CHN"] = L"7.换刀移动速度",
                   [L"POL"] = L"7.Zmien Predkosc Narz.",
                   [L"ENG"] = L"7.Change tool speed",},

    [L"存储空间不够，生成文件失败!"] = {
                   [L"CHN"] = L"存储空间不够，生成文件失败!",
                   [L"POL"] = L"Brak pamieci\nGenerowanie\nkodu\nnie powiodlo sie!",
                   [L"ENG"] = L"No enough\nmemory,\nGenerate\ncode\nfailed!",},

    [L"1.空程速度"] = {
                   [L"CHN"] = L"1.空程速度",
                   [L"POL"] = L"1.Predkosc G00",
                   [L"ENG"] = L"1.G00 speed",},

    [L"1.回机械原点"] = {
                   [L"CHN"] = L"1.回机械原点",
                   [L"POL"] = L"1.Powrot do punktu zerowego",
                   [L"ENG"] = L"1.Back REF Point",},

    [L"2. Y轴回退距离"] = {
                   [L"CHN"] = L"2. Y轴回退距离",
                   [L"POL"] = L"2.Y Retract Dist",
                   [L"ENG"] = L"2.Y Retract Dist",},

    [L"空程速度"] = {
                   [L"CHN"] = L"空程速度",
                   [L"POL"] = L"Predkosc G00",
                   [L"ENG"] = L"G00 speed",},

    [L"8.换刀前置点"] = {
                   [L"CHN"] = L"8.换刀前置点",
                   [L"POL"] = L"8.Pozycja przed wymiana narzedzi",
                   [L"ENG"] = L"8.Pre-TC pos",},

    [L"是否升级系统?"] = {
                   [L"CHN"] = L"是否升级系统?",
                   [L"POL"] = L"Aktualizowac System?",
                   [L"ENG"] = L"Update The  System?",},

    [L"10清除临时文件"] = {
                   [L"CHN"] = L"10清除临时文件",
                   [L"POL"] = L"10.Usun info",
                   [L"ENG"] = L"10.Delete info",},

    [L"回机械原点方向"] = {
                   [L"CHN"] = L"回机械原点方向",
                   [L"POL"] = L"Kierunek Bazowania",
                   [L"ENG"] = L"Homing Direction",},

    [L"───"] = {
                   [L"CHN"] = L"───",
                   [L"POL"] = L"──",
                   [L"ENG"] = L"──",},

    [L"立即执行"] = {
                   [L"CHN"] = L"立即执行",
                   [L"POL"] = L"Wykonaj",
                   [L"ENG"] = L"Execute Now",},

    [L"* 脉冲当量"] = {
                   [L"CHN"] = L"* 脉冲当量",
                   [L"POL"] = L"* P Ekwiw.",
                   [L"ENG"] = L"* P Equiv",},

    [L"* Y 轴为旋转轴"] = {
                   [L"CHN"] = L"* Y 轴为旋转轴",
                   [L"POL"] = L" * Y jako Os Obrotowa",
                   [L"ENG"] = L" * Y as   Rotary Axis",},

    [L"自动"] = {
                   [L"CHN"] = L"自动",
                   [L"POL"] = L"Auto",
                   [L"ENG"] = L"Auto",},

    [L"2.载入上次结果"] = {
                   [L"CHN"] = L"2.载入上次结果",
                   [L"POL"] = L"2.Wczytaj ostatni",
                   [L"ENG"] = L"2.Load The Last",},

    [L"文件"] = {
                   [L"CHN"] = L"文件",
                   [L"POL"] = L"Plik",
                   [L"ENG"] = L"File",},

    [L"文件:"] = {
                   [L"CHN"] = L"文件:",
                   [L"POL"] = L"Plik:",                   
                   [L"ENG"] = L"File:",},

    [L"正方向"] = {
                   [L"CHN"] = L"正方向",
                   [L"POL"] = L"Dodatni",
                   [L"ENG"] = L"Positive",},
    
    [L"负方向"] = {
                   [L"CHN"] = L"负方向",
                   [L"POL"] = L"Ujemny",
                   [L"ENG"] = L"Negative",},
    
    [L"X 轴方向"] = {
                   [L"CHN"] = L"X 轴方向",
                   [L"POL"] = L"Kierunek X",
                   [L"ENG"] = L"Direction Of X",},
     
    [L"Y 轴方向"] = {
                   [L"CHN"] = L"Y 轴方向",
                   [L"POL"] = L"Kierunek Y",
                   [L"ENG"] = L"Direction Of Y",},
     
    [L"Z 轴方向"] = {
                   [L"CHN"] = L"Z 轴方向",
                   [L"POL"] = L"Kierunek osi Z",
                   [L"ENG"] = L"Direction Of Z",},
     
    [L"4.已注册次数"] = {
                   [L"CHN"] = L"4.已注册次数",
                   [L"POL"] = L"4.Ilosc rejestrowan",
                   [L"ENG"] = L"4.Register Times",},

    [L"剩余时间"] = {
                   [L"CHN"] = L"剩余时间",
                   [L"POL"] = L"Pozostaly czas",
                   [L"ENG"] = L"Remaining Time",},

    [L"横铣"] = {
                   [L"CHN"] = L"横铣",
                   [L"POL"] = L"Frez. Poziome",
                   [L"ENG"] = L"Horiz. Mil",},
                   
    [L"纵铣"] = {
                   [L"CHN"] = L"纵铣",
                   [L"POL"] = L"Dlugie frezowanie",
                   [L"ENG"] = L"Long Mill",},

    [L"正向"] = {
                   [L"CHN"] = L"正向",
                   [L"POL"] = L"Forword",
                   [L"ENG"] = L"Forword",},
                   
    [L"负向"] = {
                   [L"CHN"] = L"负向",
                   [L"POL"] = L"Reverse",
                   [L"ENG"] = L"Reverse",},

    [L"2.板卡号"] = {
                   [L"CHN"] = L"2.板卡号",
                   [L"POL"] = L"2.Karta Nr",
                   [L"ENG"] = L"2.Card No.",},

    [L"已注册次数"] = {
                   [L"CHN"] = L"已注册次数",
                   [L"POL"] = L"Ilosc zarejestrowan",
                   [L"ENG"] = L"Registered Times",},

    [L"板卡号"] = {
                   [L"CHN"] = L"板卡号",
                   [L"POL"] = L"Numer karty",
                   [L"ENG"] = L"Card No.",},
    [L"X 轴: "] = {
                   [L"CHN"] = L"X 轴: ",
                   [L"POL"] = L"X :",
                   [L"ENG"] = L"X :",},
                   
    [L"Y 轴: "] = {
                   [L"CHN"] = L"Y 轴: ",
                   [L"POL"] = L"Y :",
                   [L"ENG"] = L"Y :",},
                   
    [L"Z 轴: "] = {
                   [L"CHN"] = L"Z 轴: ",
                   [L"POL"] = L"Z :",
                   [L"ENG"] = L"Z :",},

    [L"天:%d"] = {
                   [L"CHN"] = L"天:%d",
                   [L"POL"] = L"Dni:%d",
                   [L"ENG"] = L"Days:%d",},

    [L"3.剩余时间"] = {
                   [L"CHN"] = L"3.剩余时间",
                   [L"POL"] = L"3.Pozostaly czas",
                   [L"ENG"] = L"3.Remaining Time",},

    [L"循环"] = {
                   [L"CHN"] = L"循环",
                   [L"POL"] = L"Cycle",
                   [L"ENG"] = L"Cycle",},

    [L"刀具长度"] = {
                   [L"CHN"] = L"刀具长度",
                   [L"POL"] = L"Dlugosc Narz.",
                   [L"ENG"] = L"Tool Leng-th",},

    [L"原点"] = {
                   [L"CHN"] = L"原点",
                   [L"POL"] = L"ORG",
                   [L"ENG"] = L"ORG",},

    [L"步进"] = {
                   [L"CHN"] = L"步进",
                   [L"POL"] = L"Krok",
                   [L"ENG"] = L"Stepping",},
                   
    [L"不能小于"] = {
                   [L"CHN"] = L"不能小于",
                   [L"POL"] = L"Nie moze byc mniej niz",
                   [L"ENG"] = L"can not be  less than",},

    [L"删除日志成功!"] = {
                   [L"CHN"] = L"删除日志成功!",
                   [L"POL"] = L"Udana proba usuniecia pliku dziennika!",
                   [L"ENG"] = L"Log Deleted Successfully!",},

    [L"G58 工件偏置"] = {
                   [L"CHN"] = L"G58 工件偏置",
                   [L"POL"] = L"Odsuniecie G58",
                   [L"ENG"] = L"G58 Offset",},

    [L"0:不处理1:Z 单独2:XYZ 联动"] = {
                   [L"CHN"] = L"0:不处理1:Z 单独2:XYZ 联动",
                   [L"POL"] = L"0:Not 1:Z single 2:XYZ all",
                   [L"ENG"] = L"0:Not 1:Z single 2:XYZ all",},

    [L"1.启用自动润滑"] = {
                   [L"CHN"] = L"1.启用自动润滑",
                   [L"POL"] = L"1.Wlacz Auto Smarowanie",
                   [L"ENG"] = L"1.EnableAutoLube",},

    [L"换刀移动速度"] = {
                   [L"CHN"] = L"换刀移动速度",
                   [L"POL"] = L"Zmien predkosc narzedzia",
                   [L"ENG"] = L"Change to-ol speed",},

    [L" Y轴回退距离"] = {
                   [L"CHN"] = L" Y轴回退距离",
                   [L"POL"] = L"Odleglosc wycofania osi Y",
                   [L"ENG"] = L"Retract   Distance Of Y",},

    [L"C:      [OK]选择"] = {
                   [L"CHN"] = L"C:      [OK]选择",
                   [L"POL"] = L"C:      [OK]Select",
                   [L"ENG"] = L"C:      [OK]Select",},

    [L"4.加工时间范围"] = {
                   [L"CHN"] = L"4.加工时间范围",
                   [L"POL"] = L"4.Info Maszyny",
                   [L"ENG"] = L"4.Machining Info",},

    [L"16. 红灯提示"] = {
                   [L"CHN"] = L"16. 红灯提示",
                   [L"POL"] = L"16.Wskazowka zakonczenia",
                   [L"ENG"] = L"16.ProcessEndTip",},

    [L"9.Z 轴进刀方式"] = {
                   [L"CHN"] = L"9.Z 轴进刀方式",
                   [L"POL"] = L"9.Z Down Option",
                   [L"ENG"] = L"9.Z Down Option",},

    [L"短线段最高速度限速长度"] = {
                   [L"CHN"] = L"短线段最高速度限速长度",
                   [L"POL"] = L"Dlugosc limitu krotkiego segmentuLength Of Short Seg.Spdlmt",
                   [L"ENG"] = L"Length Of Short Seg.Spdlmt",},

    [L"导出日志成功!"] = {
                   [L"CHN"] = L"导出日志成功!",
                   [L"POL"] = L"Plik dziennika zostal pomyslnie eksportowany!",
                   [L"ENG"] = L"Log ExportedSuccessfully!",},

    [L"发现U盘,浏览该盘文件?"] = {
                   [L"CHN"] = L"发现U盘,浏览该盘文件?",
                   [L"POL"] = L"Znaleziono dysk USB,skanowac ?",
                   [L"ENG"] = L"Find U-disk,scan it?",},

    [L"U:      [OK]选择"] = {
                   [L"CHN"] = L"U:      [OK]选择",
                   [L"POL"] = L"U:      [OK]Select",
                   [L"ENG"] = L"U:      [OK]Select",},

    [L"6.LED 灯检测"] = {
                   [L"CHN"] = L"6.LED 灯检测",
                   [L"POL"] = L"6.LED Diag",
                   [L"ENG"] = L"6.LED Diag",},

    [L"上次文件非Nc文件，是否需要加载？"] = {
                   [L"CHN"] = L"上次文件非Nc文件，是否需要加载？",
                   [L"POL"] = L"Ostatni nie jest plikiem Nc, OK aby wczytac?",
                   [L"ENG"] = L"Last is not Nc file, OK to load it?",},

    [L"删除临时文件成功!"] = {
                   [L"CHN"] = L"删除临时文件成功!",
                   [L"POL"] = L"Plik Info usuniety!",
                   [L"ENG"] = L"Info File   Deleted!",},

    [L"6.旋转轴加速度"] = {
                   [L"CHN"] = L"6.旋转轴加速度",
                   [L"POL"] = L"6.Przysp. Obrotowej osi Y",
                   [L"ENG"] = L"6.Rotary Y Acc.",},

    [L"5.旋转轴起跳速度"] = {
                   [L"CHN"] = L"5.旋转轴起跳速度",
                   [L"POL"] = L"5.Przyspieszenie poczatkowe obrotu",
                   [L"ENG"] = L"5.Rotary Takeoff",},

    [L"2.轴输出方向"] = {
                   [L"CHN"] = L"2.轴输出方向",
                   [L"POL"] = L"2.Kierunek osi",
                   [L"ENG"] = L"2.Axis OutpDir",},

    [L"语言选择成功，立即重启?"] = {
                   [L"CHN"] = L"语言选择成功，立即重启?",
                   [L"POL"] = L"Przelaczono! Zrestartowac?",
                   [L"ENG"] = L"Switched!   Reboot Now?",},

    [L"Y 正限位"] = {
                   [L"CHN"] = L"Y 正限位",
                   [L"POL"] = L"Limit +Y",
                   [L"ENG"] = L"Y +Limit",},

    [L"X 正限位"] = {
                   [L"CHN"] = L"X 正限位",
                   [L"POL"] = L"Limit +X",
                   [L"ENG"] = L"X +Limit",},

    [L"执行加工程序失败！"] = {
                   [L"CHN"] = L"执行加工程序失败！",
                   [L"POL"] = L"Nieudana proba uruchomienia programu!",
                   [L"ENG"] = L"Failed to execute the processing program!",},

    [L"3.刀具设置"] = {
                   [L"CHN"] = L"3.刀具设置",
                   [L"POL"] = L"3.Ustawienie narzedzia",
                   [L"ENG"] = L"3.Tool Set",},

    [L"18. 转角光顺类型"] = {
                   [L"CHN"] = L"18. 转角光顺类型",
                   [L"POL"] = L"18.Corner Option",
                   [L"ENG"] = L"18.Corner Option",},

    [L"4.暂停时抬刀量"] = {
                   [L"CHN"] = L"4.暂停时抬刀量",
                   [L"POL"] = L"4.Podniesienie przy Pauzie",
                   [L"ENG"] = L"4.Lifts on Pause",},

    [L"G54 工件偏置"] = {
                   [L"CHN"] = L"G54 工件偏置",
                   [L"POL"] = L"Odsuniecie G54",
                   [L"ENG"] = L"G54 Offset",},

    [L"导出参数文件失败!"] = {
                   [L"CHN"] = L"导出参数文件失败!",
                   [L"POL"] = L"  Nieudany Eksport!",
                   [L"ENG"] = L"   Export     Failed!",},

    [L"3.加工操作"] = {
                   [L"CHN"] = L"3.加工操作",
                   [L"POL"] = L"3.Operacje",
                   [L"ENG"] = L"3.Operations",},

    [L"注册成功, 可以正常使用"] = {
                   [L"CHN"] = L"注册成功, 可以正常使用",
                   [L"POL"] = L"Rejestracja zakonczona!",
                   [L"ENG"] = L"RegistrationCompletes!",},

    [L"文件不存在！"] = {
                   [L"CHN"] = L"文件不存在！",
                   [L"POL"] = L"Plik nie istnieje!",
                   [L"ENG"] = L"No file exist!",},

    [L"连续"] = {
                   [L"CHN"] = L"连续",
                   [L"POL"] = L"Jog",
                   [L"ENG"] = L"Jog",},

    [L"2.对刀块Y 坐标"] = {
                   [L"CHN"] = L"2.对刀块Y 坐标",
                   [L"POL"] = L"2.Wspolrzedne Kalib. Y",
                   [L"ENG"] = L"2.Y Cali Coor",},

    [L"未找到U 盘!"] = {
                   [L"CHN"] = L"未找到U 盘!",
                   [L"POL"] = L"Dysk USB nie odnaleziony!",
                   [L"ENG"] = L" U-disk Is   Not Found!",},

    [L"3.使用mm作单位"] = {
                   [L"CHN"] = L"3.使用mm作单位",
                   [L"POL"] = L"3.mm jako Jednostka",
                   [L"ENG"] = L"3.mm As Unit",},

    [L"|T|该物理地址已被其它端口使用!"] = {
                   [L"CHN"] = L"|T|该物理地址已被其它端口使用!",
                   [L"POL"] = L"|T|Adres zostal uzyty przez inny port!",
                   [L"ENG"] = L"|T|The physical address has been used by other port!",},

    [L"* 主轴最大转速"] = {
                   [L"CHN"] = L"* 主轴最大转速",
                   [L"POL"] = L" * Maks. Predk. Wrzeciona",
                   [L"ENG"] = L" * Max.   Spindle Speed",},

    [L"6.主轴设置"] = {
                   [L"CHN"] = L"6.主轴设置",
                   [L"POL"] = L"6.Ust. Wrzeciona",
                   [L"ENG"] = L"6.Spindle Set",},

    [L"A"] = {
                   [L"CHN"] = L"A",
                   [L"POL"] = L"B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X","Y","Z",
                   [L"ENG"] = L"B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X","Y","Z",},

    [L"软件版本"] = {
                   [L"CHN"] = L"软件版本",
                   [L"POL"] = L"Wersja Oprogramowania",
                   [L"ENG"] = L"Software Version",},

    [L"断点无效"] = {
                   [L"CHN"] = L"断点无效",
                   [L"POL"] = L"Niewlasciwy punkt przerwania!",
                   [L"ENG"] = L"Invalid bre-ak point!",},

    [L"发送微调指令失败，请重试！"] = {
                   [L"CHN"] = L"发送微调指令失败，请重试！",
                   [L"POL"] = L"Nieudana proba wyslania \nkomendy,\nSprobuj ponownie!",
                   [L"ENG"] = L"Fail to sendjiggle\ncommand,\nTry again!",},

    [L"%d.刀补号%d"] = {
                   [L"CHN"] = L"%d.刀补号%d",
                   [L"POL"] = L"%d.Narzedzie%d",
                   [L"ENG"] = L"%d.Tool%d",},

    [L"释放"] = {
                   [L"CHN"] = L"释放",
                   [L"POL"] = L"Zwolnienie",
                   [L"ENG"] = L"Release",},

    [L"6.Z 轴最大速度"] = {
                   [L"CHN"] = L"6.Z 轴最大速度",
                   [L"POL"] = L"6.Maks.Predk. Z",
                   [L"ENG"] = L"6.Max.Speed of Z",},

    [L"* 停止时停主轴"] = {
                   [L"CHN"] = L"* 停止时停主轴",
                   [L"POL"] = L"* Wrzeciono wylacz gdy zatrzymany program",
                   [L"ENG"] = L"* Spindle OFF When Stop",},

    [L"9.就近点加工"] = {
                   [L"CHN"] = L"9.就近点加工",
                   [L"POL"] = L"9.Nearby Process",
                   [L"ENG"] = L"9.Nearby Process",},

    [L" Z轴回退距离"] = {
                   [L"CHN"] = L" Z轴回退距离",
                   [L"POL"] = L"Odleglosc powrotu osi Z",
                   [L"ENG"] = L"Retract   Distance Of Z",},

    [L"系统忙!"] = {
                   [L"CHN"] = L"系统忙!",
                   [L"POL"] = L"System przetwarza!",
                   [L"ENG"] = L"System is   busy!",},

    [L"5.导入参数"] = {
                   [L"CHN"] = L"5.导入参数",
                   [L"POL"] = L"5.Importuj Parametry",
                   [L"ENG"] = L"5.Import Params",},

    [L"导出日志失败!"] = {
                   [L"CHN"] = L"导出日志失败!",
                   [L"POL"] = L"Nieudany eksport dziennika!",
                   [L"ENG"] = L"Failed to   Export Log!",},

    [L"G55 工件偏置"] = {
                   [L"CHN"] = L"G55 工件偏置",
                   [L"POL"] = L"Odsuniecie G55",
                   [L"ENG"] = L"G55 Offset",},

    [L"2.设置当前刀具号"] = {
                   [L"CHN"] = L"2.设置当前刀具号",
                   [L"POL"] = L"2.Aktualny numer narz.",
                   [L"ENG"] = L"2.CurrentToolNo.",},

    [L"6.参数维护"] = {
                   [L"CHN"] = L"6.参数维护",
                   [L"POL"] = L"6.Aktualizacja Param.",
                   [L"ENG"] = L"6.Param Upkeep",},

    [L"立即载入"] = {
                   [L"CHN"] = L"立即载入",
                   [L"POL"] = L"Wczytaj",
                   [L"ENG"] = L"Load Now",},

    [L"2.端口列表"] = {
                   [L"CHN"] = L"2.端口列表",
                   [L"POL"] = L"2.Lista Portow",
                   [L"ENG"] = L"2.Port List",},

    [L"空闲"] = {
                   [L"CHN"] = L"空闲",
                   [L"POL"] = L"Stan Oczekiwania",
                   [L"ENG"] = L"Idle",},

    [L"固定对刀块Y 机械坐标"] = {
                   [L"CHN"] = L"固定对刀块Y 机械坐标",
                   [L"POL"] = L"Wspolrzedna Masz. Y czujnika dl. narzedzia",
                   [L"ENG"] = L"Y MEC Coor of Cali block",},

    [L"3.恢复出厂参数"] = {
                   [L"CHN"] = L"3.恢复出厂参数",
                   [L"POL"] = L"3.Parametry fabryczne",
                   [L"ENG"] = L"3.Factory Params",},

    [L"5.G58 工件偏置"] = {
                   [L"CHN"] = L"5.G58 工件偏置",
                   [L"POL"] = L"5.Odsuniecie G58",
                   [L"ENG"] = L"5.G58 Offset",},

    [L"拷贝文件失败，请检查U 盘是否插好！"] = {
                   [L"CHN"] = L"拷贝文件失败，请检查U 盘是否插好！",
                   [L"POL"] = L"Nieudana proba kopiowania pliku!",
                   [L"ENG"] = L"File Copy failure, please check whether the floppy disk is well inserted!",},

    [L"限位释放"] = {
                   [L"CHN"] = L"限位释放",
                   [L"POL"] = L"Zwolnienie Limitu",
                   [L"ENG"] = L"LmitRls.",},

    [L"11. 圆弧增量模式"] = {
                   [L"CHN"] = L"11. 圆弧增量模式",
                   [L"POL"] = L"11 Przyrost Luku",
                   [L"ENG"] = L"11Arc Increment",},

    [L"* 是否使用1.5ms 控制周期"] = {
                   [L"CHN"] = L"* 是否使用1.5ms 控制周期",
                   [L"POL"] = L"Using 1.5ms control cycle?",
                   [L"ENG"] = L"Using 1.5ms control cycle?",},

    [L"4.操作员参数"] = {
                   [L"CHN"] = L"4.操作员参数",
                   [L"POL"] = L"4.Parametry Operatora",
                   [L"ENG"] = L"4.Oper Param",},

    [L"13. 回原点标志"] = {
                   [L"CHN"] = L"13. 回原点标志",
                   [L"POL"] = L"13 Znak powrotu do punktu zerowego",
                   [L"ENG"] = L"13Sign of BK REF_P",},

    [L"|M|端口配置文件格式有错!"] = {
                   [L"CHN"] = L"|M|端口配置文件格式有错!",
                   [L"POL"] = L"|M|Problem z formatem pliku konfiguracyjnego!",
                   [L"ENG"] = L"|M|There is a problem with the format of port configuration file!",},

    [L"7.Y 旋转轴设置"] = {
                   [L"CHN"] = L"7.Y 旋转轴设置",
                   [L"POL"] = L"7.Os obrotowa Y",
                   [L"ENG"] = L"7.Y Rotaryaxis",},

    [L"未回机械原点!"] = {
                   [L"CHN"] = L"未回机械原点!",
                   [L"POL"] = L"Nie zostal zbazowany!",
                   [L"ENG"] = L"Have not    homed yet!",},

    [L"17. 对刀抬刀高度"] = {
                   [L"CHN"] = L"17. 对刀抬刀高度",
                   [L"POL"] = L"17.Wysokosc Kalibr. Narz.",
                   [L"ENG"] = L"17.CaliToolHeight",},

    [L"14. 安全高度"] = {
                   [L"CHN"] = L"14. 安全高度",
                   [L"POL"] = L"14Bezpieczna Wysokosc",
                   [L"ENG"] = L"14Safety Height",},

    [L"2.浏览U 盘文件"] = {
                   [L"CHN"] = L"2.浏览U 盘文件",
                   [L"POL"] = L"2.Pliki USB",
                   [L"ENG"] = L"2.USB Files",},

    [L"14. 规划前瞻距离"] = {
                   [L"CHN"] = L"14. 规划前瞻距离",
                   [L"POL"] = L"14Look Ahead Distance",
                   [L"ENG"] = L"14Look Ahead Distance",},

    [L" X轴回退距离"] = {
                   [L"CHN"] = L" X轴回退距离",
                   [L"POL"] = L"Odleglosc powrotu osi X",
                   [L"ENG"] = L"Retract   Distance Of X",},

    [L"加工前回原点"] = {
                   [L"CHN"] = L"加工前回原点",
                   [L"POL"] = L"Powrot do punktu zerowego przed obrobka",
                   [L"ENG"] = L"Back REFP before machining",},

    [L"  OK  取消"] = {
                   [L"CHN"] = L"  OK  取消",
                   [L"POL"] = L"  OK  Anuluj",
                   [L"ENG"] = L"  OK  Cancle",},

    [L"按[OK]键设置当前位置为停车位置, 按[ESC] 返回"] = {
                   [L"CHN"] = L"按[OK]键设置当前位置为停车位置, 按[ESC] 返回",
                   [L"POL"] = L"Ustaw aktualna pozycje jako poz. parkowaniaSet current pos as park pos. by [OK] key,return by [ESC] key.",
                   [L"ENG"] = L"Set current pos as park pos. by [OK] key,return by [ESC] key.",},

    [L"工件坐标系"] = {
                   [L"CHN"] = L"工件坐标系",
                   [L"POL"] = L"WCS",
                   [L"ENG"] = L"WCS",},

    [L"5.输出端口检测"] = {
                   [L"CHN"] = L"5.输出端口检测",
                   [L"POL"] = L"5.Diagnostyka portu wyjscia",
                   [L"ENG"] = L"5.Outport Diag",},

    [L"总行数: "] = {
                   [L"CHN"] = L"总行数: ",
                   [L"POL"] = L"Calkowity:",
                   [L"ENG"] = L"Total:",},

    [L"OK: 选择"] = {
                   [L"CHN"] = L"OK: 选择",
                   [L"POL"] = L"OK:Select",
                   [L"ENG"] = L"OK:Select",},

    [L" <无文件>"] = {
                   [L"CHN"] = L" <无文件>",
                   [L"POL"] = L" <Brak pliku>",
                   [L"ENG"] = L" <No File>",},

    [L"没有加载文件! "] = {
                   [L"CHN"] = L"没有加载文件! ",
                   [L"POL"] = L"No file loaded!",
                   [L"ENG"] = L"No file loaded!",},

    [L"换刀前置点"] = {
                   [L"CHN"] = L"换刀前置点",
                   [L"POL"] = L"Pozycja przed wymiana narzedzi",
                   [L"ENG"] = L"Pre-TC pos",},

    [L"3.主轴初始档位"] = {
                   [L"CHN"] = L"3.主轴初始档位",
                   [L"POL"] = L"3.Bieg Podst.",
                   [L"ENG"] = L"3.Initial Gear",},

    [L"X "] = {
                   [L"CHN"] = L"X ",
                   [L"POL"] = L"Y ", "Z ", "X*", "Y*","Z*",
                   [L"ENG"] = L"Y ", "Z ", "X*", "Y*","Z*",},

    [L"1.主轴档位数"] = {
                   [L"CHN"] = L"1.主轴档位数",
                   [L"POL"] = L"1.Biegi Wrzeciona",
                   [L"ENG"] = L"1.Spindle Gears",},

    [L"1.是否循环加工"] = {
                   [L"CHN"] = L"1.是否循环加工",
                   [L"POL"] = L"1.Cykl Przetw.",
                   [L"ENG"] = L"1.Cycle Process",},

    [L"必须在%d和%d之间!"] = {
                   [L"CHN"] = L"必须在%d和%d之间!",
                   [L"POL"] = L"\nmusi byc\npomiedzy %d\n i %d!  ",
                   [L"ENG"] = L"\nmust be\nbetween %d\nand %d!  ",},

    [L"加工次数"] = {
                   [L"CHN"] = L"加工次数",
                   [L"POL"] = L" Ilosc Cykli",
                   [L"ENG"] = L" Cycle    Times",},

    [L"2.各轴反向间隙"] = {
                   [L"CHN"] = L"2.各轴反向间隙",
                   [L"POL"] = L"2.Luz osiowy",
                   [L"ENG"] = L"2.AxisBacklash",},

    [L"刀号:%d  "] = {
                   [L"CHN"] = L"刀号:%d  ",
                   [L"POL"] = L"Narzedzie nr:%d  ",
                   [L"ENG"] = L"Tool No.:%d  ",},

    [L"高速"] = {
                   [L"CHN"] = L"高速",
                   [L"POL"] = L"Wysoko",
                   [L"ENG"] = L"High",},

    [L"轨迹平滑时间"] = {
                   [L"CHN"] = L"轨迹平滑时间",
                   [L"POL"] = L"Czas wygladzania sciezki",
                   [L"ENG"] = L"Path Smoo-thing Time",},

    [L"磁盘剩余空间"] = {
                   [L"CHN"] = L"磁盘剩余空间",
                   [L"POL"] = L"Pozostala przestrzen dyskowa",
                   [L"ENG"] = L"Disk Space Left",},

    [L"刀尖间距"] = {
                   [L"CHN"] = L"刀尖间距",
                   [L"POL"] = L"Szczelina",
                   [L"ENG"] = L"NoseGap ",},

    [L"20. 设置控制周期"] = {
                   [L"CHN"] = L"20. 设置控制周期",
                   [L"POL"] = L"20Setting control cycle?",
                   [L"ENG"] = L"20Setting control cycle?",},

    [L"8.反向间隙设置"] = {
                   [L"CHN"] = L"8.反向间隙设置",
                   [L"POL"] = L"8.Ustawienie Luzu",
                   [L"ENG"] = L"8.Backlash Set",},

    [L"紧停"] = {
                   [L"CHN"] = L"紧停",
                   [L"POL"] = L"Estp",
                   [L"ENG"] = L"Estp",},

    [L"2.换刀提示"] = {
                   [L"CHN"] = L"2.换刀提示",
                   [L"POL"] = L"2.Wskazowka Wym. Narz.",
                   [L"ENG"] = L"2.ToolChangeTip",},

    [L"1.速度参数"] = {
                   [L"CHN"] = L"1.速度参数",
                   [L"POL"] = L"1.Predkosc",
                   [L"ENG"] = L"1.Velocity",},

    [L"文件删除成功!"] = {
                   [L"CHN"] = L"文件删除成功!",
                   [L"POL"] = L"Plik pomyslnie zostal usuniety",
                   [L"ENG"] = L"The File    Is Deleted  Successfully",},

    [L"2.选择停车位置"] = {
                   [L"CHN"] = L"2.选择停车位置",
                   [L"POL"] = L"2.Wybierz miejsce",
                   [L"ENG"] = L"2.Select Site",},

    [L"* 抬刀高度"] = {
                   [L"CHN"] = L"* 抬刀高度",
                   [L"POL"] = L"* Wysokosc Podnoszenia",
                   [L"ENG"] = L"* Lifting Height",},

    [L"旋转轴起跳速度"] = {
                   [L"CHN"] = L"旋转轴起跳速度",
                   [L"POL"] = L"Predkosc pocz. osi obr. Y",
                   [L"ENG"] = L"Takeoff S-peed of Rotary Y",},

    [L"5.停车设置"] = {
                   [L"CHN"] = L"5.停车设置",
                   [L"POL"] = L"5.Miejsce Park. MCS",
                   [L"ENG"] = L"5.Park MCS Site",},

    [L"C:      [OK]载入"] = {
                   [L"CHN"] = L"C:      [OK]载入",
                   [L"POL"] = L"C:      [OK]Wczytaj",
                   [L"ENG"] = L"C:      [OK]Load",},

    [L"Y 始坐标"] = {
                   [L"CHN"] = L"Y 始坐标",
                   [L"POL"] = L"Pocz. Y",
                   [L"ENG"] = L"Y Init",},

    [L"X 始坐标"] = {
                   [L"CHN"] = L"X 始坐标",
                   [L"POL"] = L"Pocz. X",
                   [L"ENG"] = L"X Init",},

    [L"生成后的加工文件将大于50M\n生成文件失败？"] = {
                   [L"CHN"] = L"生成后的加工文件将大于50M\n生成文件失败？",
                   [L"POL"] = L"Plik\npo\nwygenerowaniu\nbedzie wiekszy niz 50M.\nGenerowanie\nkodu\nnie powiodlo sie!",
                   [L"ENG"] = L"The file\nafter\ngenerated\nwill be big than 50M.\nGenerate\ncode\nfailed!",},

    [L"固定对刀块Z 机械坐标"] = {
                   [L"CHN"] = L"固定对刀块Z 机械坐标",
                   [L"POL"] = L"Wsp. Masz. Plytki Kalibr. Z",
                   [L"ENG"] = L"Z MEC Coor of Cali block",},

    [L"3.加工时间间隔"] = {
                   [L"CHN"] = L"3.加工时间间隔",
                   [L"POL"] = L"3.Interwal cykli",
                   [L"ENG"] = L"3.Cycle Interval",},

    [L"1.刀库容量  "] = {
                   [L"CHN"] = L"1.刀库容量  ",
                   [L"POL"] = L"1.Poj. Magazynka",
                   [L"ENG"] = L"1.ATC Capacity",},

    [L"拷贝文件失败!"] = {
                   [L"CHN"] = L"拷贝文件失败!",
                   [L"POL"] = L"Nieudana proba kopiowania!",
                   [L"ENG"] = L"File copy failure!",},

    [L"每次润滑的持续时间"] = {
                   [L"CHN"] = L"每次润滑的持续时间",
                   [L"POL"] = L" Czas trwania smarowania",
                   [L"ENG"] = L" Duration For Each Lube",},

    [L"        [OK]选择"] = {
                   [L"CHN"] = L"        [OK]选择",
                   [L"POL"] = L"      [OK]Wybierz",
                   [L"ENG"] = L"      [OK]Select",},

    [L"1.Y 轴为旋转轴"] = {
                   [L"CHN"] = L"1.Y 轴为旋转轴",
                   [L"POL"] = L"1.Y Jako Os Obr.",
                   [L"ENG"] = L"1.Y AsRotaryAxis",},

    [L"Z 负限位"] = {
                   [L"CHN"] = L"Z 负限位",
                   [L"POL"] = L"Limit -Z",
                   [L"ENG"] = L"Z -Limit",},

    [L"Y 负限位"] = {
                   [L"CHN"] = L"Y 负限位",
                   [L"POL"] = L"Limit -Y",
                   [L"ENG"] = L"Y -Limit",},

    [L"X 负限位"] = {
                   [L"CHN"] = L"X 负限位",
                   [L"POL"] = L"Limit -X",
                   [L"ENG"] = L"X -Limit",},

    [L"3.持续时间"] = {
                   [L"CHN"] = L"3.持续时间",
                   [L"POL"] = L"3.Czas trwania",
                   [L"ENG"] = L"3.Duration",},

    [L"3.刀间距"] = {
                   [L"CHN"] = L"3.刀间距",
                   [L"POL"] = L"3.Krok Narzedzia",
                   [L"ENG"] = L"3.Tool step",},

    [L"循环加工时间间隔"] = {
                   [L"CHN"] = L"循环加工时间间隔",
                   [L"POL"] = L"Interwal Cykli Przetwarzania",
                   [L"ENG"] = L"Interval  of Cycle Process",},

    [L"* 行程上限"] = {
                   [L"CHN"] = L"* 行程上限",
                   [L"POL"] = L"Gorny Limit Skoku",
                   [L"ENG"] = L"StrkUpperLmt",},

    [L"生成文件失败!"] = {
                   [L"CHN"] = L"生成文件失败!",
                   [L"POL"] = L"Generowanie\nkodu\nnieudane!",
                   [L"ENG"] = L"Generate\ncode\nfailed!",},

    [L"1.公共偏置"] = {
                   [L"CHN"] = L"1.公共偏置",
                   [L"POL"] = L"1.Wspolne Odsuniecie",
                   [L"ENG"] = L"1.PublicOffset",},

    [L"7.旋转轴最大速度"] = {
                   [L"CHN"] = L"7.旋转轴最大速度",
                   [L"POL"] = L"7.Maks. Predk. Katowa",
                   [L"ENG"] = L"7.Max.RotaryVel.",},

    [L"U:      [OK]载入"] = {
                   [L"CHN"] = L"U:      [OK]载入",
                   [L"POL"] = L"U:      [OK]Wczytaj",
                   [L"ENG"] = L"U:      [OK]Load",},

    [L"加工结束停主轴"] = {
                   [L"CHN"] = L"加工结束停主轴",
                   [L"POL"] = L" Wyl. Wrzeciono po zakonczeniu",
                   [L"ENG"] = L" Spindle  Off When Finish",},

    [L"3.首点作为零点"] = {
                   [L"CHN"] = L"3.首点作为零点",
                   [L"POL"] = L"3.Pierwszy punkt jako 0",
                   [L"ENG"] = L"3.1st Point As 0",},

    [L"7.系统维护"] = {
                   [L"CHN"] = L"7.系统维护",
                   [L"POL"] = L"7.Aktualizacja Systemu",
                   [L"ENG"] = L"7.System Upkeep",},

    [L"─"] = {
                   [L"CHN"] = L"─",
                   [L"POL"] = L"-",
                   [L"ENG"] = L"-",},

    [L"9.屏蔽S 指令"] = {
                   [L"CHN"] = L"9.屏蔽S 指令",
                   [L"POL"] = L"9.Ignoruj kod S",
                   [L"ENG"] = L"9.Ignore S Code",},

    [L"运行"] = {
                   [L"CHN"] = L"运行",
                   [L"POL"] = L"Uruchom",
                   [L"ENG"] = L"Run",},

    [L"时间:"] = {
                   [L"CHN"] = L"时间:",
                   [L"POL"] = L"Time:",
                   [L"ENG"] = L"Time:",},

    [L"2.恢复备份参数"] = {
                   [L"CHN"] = L"2.恢复备份参数",
                   [L"POL"] = L"2.Przywroc Kopie Zap.",
                   [L"ENG"] = L"2.Restore Backup",},

    [L"原地不动"] = {
                   [L"CHN"] = L"原地不动",
                   [L"POL"] = L"Nie ruszaj",
                   [L"ENG"] = L"Not move",},

    [L"进给倍率为0"] = {
                   [L"CHN"] = L"进给倍率为0",
                   [L"POL"] = L"Stopien posuwu jest 0!",
                   [L"ENG"] = L"Feedrate ov-erride is 0!",},

    [L"1.减速距离"] = {
                   [L"CHN"] = L"1.减速距离",
                   [L"POL"] = L"1.Odleglosc Zwalniania",
                   [L"ENG"] = L"1.Decel. Dist.",},

    [L"5.底部加工"] = {
                   [L"CHN"] = L"5.底部加工",
                   [L"POL"] = L"5.Obrobka Dna",
                   [L"ENG"] = L"5.Bottom Process",},

    [L"2.接近速度"] = {
                   [L"CHN"] = L"2.接近速度",
                   [L"POL"] = L"2.Predkosc Dojazdu",
                   [L"ENG"] = L"2.Approach Speed",},

    [L"2.旋转轴脉冲当量"] = {
                   [L"CHN"] = L"2.旋转轴脉冲当量",
                   [L"POL"] = L"2.Impuls Osi Obr. Y",
                   [L"ENG"] = L"2.Rotary Y Pulse",},

    [L"对刀后所需抬刀高度"] = {
                   [L"CHN"] = L"对刀后所需抬刀高度",
                   [L"POL"] = L"Wysokosc po Kalbr Narz.",
                   [L"ENG"] = L"Height Aft Calibrate Tool",},

    [L"操作测量刀具长度操作"] = {
                   [L"CHN"] = L"操作测量刀具长度操作",
                   [L"POL"] = L"Zmierz dlugosc narz.",
                   [L"ENG"] = L"Operate     measure tool length",},

    [L"导出参数文件成功!"] = {
                   [L"CHN"] = L"导出参数文件成功!",
                   [L"POL"] = L"Udany Eksport!",
                   [L"ENG"] = L"Successfully  Exported!",},

    [L"按K1键诊断LED 灯"] = {
                   [L"CHN"] = L"按K1键诊断LED 灯",
                   [L"POL"] = L"Press K1 key to test LED",
                   [L"ENG"] = L"Press K1 key to test LED",},

    [L"请按:"] = {
                   [L"CHN"] = L"请按:",
                   [L"POL"] = L"Nacisnij:",
                   [L"ENG"] = L"Press:",},

    [L"4.间隔时停主轴"] = {
                   [L"CHN"] = L"4.间隔时停主轴",
                   [L"POL"] = L"4.Wyl. Wrzeciona",
                   [L"ENG"] = L"4.S_Off in Intevl",},

    [L"单轴加速度"] = {
                   [L"CHN"] = L"单轴加速度",
                   [L"POL"] = L"Przysp. Poj. Osi",
                   [L"ENG"] = L" Single   Axis Acc.",},

    [L"密码输入错误！"] = {
                   [L"CHN"] = L"密码输入错误！",
                   [L"POL"] = L"Wrong Passw-ord Entered!",
                   [L"ENG"] = L"Wrong Passw-ord Entered!",},

    [L"* 旋转工件半径"] = {
                   [L"CHN"] = L"* 旋转工件半径",
                   [L"POL"] = L"* Promien prz. obr.",
                   [L"ENG"] = L"* Rotary  Workpiece Radius",},

    [L"行号:%d"] = {
                   [L"CHN"] = L"行号:%d",
                   [L"POL"] = L"Linia Nr:%d",
                   [L"ENG"] = L"Line NO.:%d",},

    [L"3.单轴加速度"] = {
                   [L"CHN"] = L"3.单轴加速度",
                   [L"POL"] = L"3.Przysp. Poj. Osi",
                   [L"ENG"] = L"3.Sgl Axis Acc.",},

    [L"5.帮助设置"] = {
                   [L"CHN"] = L"5.帮助设置",
                   [L"POL"] = L"5.Pomoc",
                   [L"ENG"] = L"5.Help",},

    [L"11. 倍率影响手动"] = {
                   [L"CHN"] = L"11. 倍率影响手动",
                   [L"POL"] = L"11.Stopien na recznym",
                   [L"ENG"] = L"11.Ratio ON MANU",},

    [L"删除临时文件失败!"] = {
                   [L"CHN"] = L"删除临时文件失败!",
                   [L"POL"] = L"NIeudana proba usuniecia pliku Info!",
                   [L"ENG"] = L"Failed to   Delete Info File !",},

    [L"结束行号"] = {
                   [L"CHN"] = L"结束行号",
                   [L"POL"] = L"Linia Koncowa",
                   [L"ENG"] = L"EndLine",},

    [L"4.G57 工件偏置"] = {
                   [L"CHN"] = L"4.G57 工件偏置",
                   [L"POL"] = L"4.Odsuniecie G57",
                   [L"ENG"] = L"4.G57 Offset",},

    [L"%s的范围需在%s和%s之间"] = {
                   [L"CHN"] = L"%s的范围需在%s和%s之间",
                   [L"POL"] = L"%s\nmusi byc pomiedzy\n%s i\n%s!",
                   [L"ENG"] = L"%s\nmust be     between\n%s and\n%s!",},

    [L"刀数:%d  "] = {
                   [L"CHN"] = L"刀数:%d  ",
                   [L"POL"] = L"Liczba Narzedzi:%d  ",
                   [L"ENG"] = L"Number of tools:%d  ",},

    [L"13. 起跳速度"] = {
                   [L"CHN"] = L"13. 起跳速度",
                   [L"POL"] = L"13Predk. Skoku",
                   [L"ENG"] = L"13Jump Speed",},

    [L"* 暂停时停主轴"] = {
                   [L"CHN"] = L"* 暂停时停主轴",
                   [L"POL"] = L"* Wylacz Wrzeciono przy Pauzie",
                   [L"ENG"] = L"* Spindle Off When Pause",},

    [L"起始行号"] = {
                   [L"CHN"] = L"起始行号",
                   [L"POL"] = L"Linia Pocz.",
                   [L"ENG"] = L"StartLine",},

    [L"2.回原点方向"] = {
                   [L"CHN"] = L"2.回原点方向",
                   [L"POL"] = L"2.Kierunek Powr. do p. zerowego",
                   [L"ENG"] = L"2.REFP Dir",},

    [L"2.刀具直径磨损量"] = {
                   [L"CHN"] = L"2.刀具直径磨损量",
                   [L"POL"] = L"2.Srednica Zuzycia Narz.",
                   [L"ENG"] = L"2.ToolDiaWear",},

    [L"已经存在，是否覆盖？"] = {
                   [L"CHN"] = L"已经存在，是否覆盖？",
                   [L"POL"] = L"jest juz obecny, nadpisac?",
                   [L"ENG"] = L"is already present,Overwrite?",},

    [L"文件已加载或者存储空间不够，复制文件失败!"] = {
                   [L"CHN"] = L"文件已加载或者存储空间不够，复制文件失败!",
                   [L"POL"] = L"Brak dostatecznej ilosci pamieci, nieudana proba kopiowania!",
                   [L"ENG"] = L"File has    loaded or No enough     memory, filecopy failure!",},

    [L"1.机床行程上限"] = {
                   [L"CHN"] = L"1.机床行程上限",
                   [L"POL"] = L"1.Gorny limit skoku",
                   [L"ENG"] = L"1.StrkUpperLmt",},

    [L"生成文件层数过多,生成时间较长,是否继续?"] = {
                   [L"CHN"] = L"生成文件层数过多,生成时间较长,是否继续?",
                   [L"POL"] = L"Zbyt wiele warstw wygenerowano, kontynuowac?",
                   [L"ENG"] = L"Too many    file layers generated,  continue?",},

    [L"是否进行Y 轴坐标清零？"] = {
                   [L"CHN"] = L"是否进行Y 轴坐标清零？",
                   [L"POL"] = L"Clear Y       coordinate?",
                   [L"ENG"] = L"Clear Y       coordinate?",},

    [L"5.加加速度"] = {
                   [L"CHN"] = L"5.加加速度",
                   [L"POL"] = L"5.Ped",
                   [L"ENG"] = L"5.Jerk",},

    [L"镜像不匹配，请联系开发商!"] = {
                   [L"CHN"] = L"镜像不匹配，请联系开发商!",
                   [L"POL"] = L"System does not match, please contact the developer!",
                   [L"ENG"] = L"System does not match, please contact the developer!",},

    [L"* 0:往复排屑; 1:高速往复排屑"] = {
                   [L"CHN"] = L"* 0:往复排屑; 1:高速往复排屑",
                   [L"POL"] = L"* 0:Lamanie wior;1:Wys. Predk. Lamanie Wior",
                   [L"ENG"] = L"* 0:Recip Chip;1:HS Recip Chip",},

    [L"  0   重启系统"] = {
                   [L"CHN"] = L"  0   重启系统",
                   [L"POL"] = L"  0   Restart",
                   [L"ENG"] = L"  0   Reboot",},

    [L"加工方式"] = {
                   [L"CHN"] = L"加工方式",
                   [L"POL"] = L"Przetwarzanie:",
                   [L"ENG"] = L"ProcessWay:",},

    [L"未加载文件!"] = {
                   [L"CHN"] = L"未加载文件!",
                   [L"POL"] = L"Nie wczytano pliku!",
                   [L"ENG"] = L"No file     loaded!",},

    [L"2.矩形平面加工"] = {
                   [L"CHN"] = L"2.矩形平面加工",
                   [L"POL"] = L"2.Obrobka Prost.",
                   [L"ENG"] = L"2.Rect Machining",},

    [L"6.G59 工件偏置"] = {
                   [L"CHN"] = L"6.G59 工件偏置",
                   [L"POL"] = L"6.Odsuniecie G59",
                   [L"ENG"] = L"6.G59 Offset",},

    [L"1.浏览本地文件"] = {
                   [L"CHN"] = L"1.浏览本地文件",
                   [L"POL"] = L"1.Pliki lokalne",
                   [L"ENG"] = L"1.Local Files",},

    [L"阵列加工不支持的功能：%s，请手工删除！"] = {
                   [L"CHN"] = L"阵列加工不支持的功能：%s，请手工删除！",
                   [L"POL"] = L"Obrobka szyku nie obsluguje tej instrukcji:%s, usun ja\nsamodzielnie!",
                   [L"ENG"] = L"Arraymachin-ing does notsupport thisinstruction:%s, remove  them by\nyourself!",},

    [L"X+:"] = {
                   [L"CHN"] = L"X+:",
                   [L"POL"] = L"Y+:", "Z+:",
                   [L"ENG"] = L"Y+:", "Z+:",},

    [L"加工文件出现严重错误，请检查并重新加载!"] = {
                   [L"CHN"] = L"加工文件出现严重错误，请检查并重新加载!",
                   [L"POL"] = L"Blad! Prosze sprawdz plik i ponownie wczytaj!",
                   [L"ENG"] = L"Error! Please check the file and reload it!",},

    [L"屏蔽F 指令"] = {
                   [L"CHN"] = L"屏蔽F 指令",
                   [L"POL"] = L" Ignoruj Kod F",
                   [L"ENG"] = L" Ignore F Code",},

    [L"%d.刀具%d"] = {
                   [L"CHN"] = L"%d.刀具%d",
                   [L"POL"] = L"%d.Narz%d",
                   [L"ENG"] = L"%d.Tool%d",},

    [L"参数保存失败!"] = {
                   [L"CHN"] = L"参数保存失败!",
                   [L"POL"] = L"Nieudana proba zapisu!",
                   [L"ENG"] = L"Save Failed!",},

    [L"删除日志失败!"] = {
                   [L"CHN"] = L"删除日志失败!",
                   [L"POL"] = L"Nieudana proba usuniecia pliku dziennika!",
                   [L"ENG"] = L"Failed to   Delete Log!",},

    [L"打开文件失败"] = {
                   [L"CHN"] = L"打开文件失败",
                   [L"POL"] = L"Nieudana proba wczytania!",
                   [L"ENG"] = L"Failed to   open file!",},

    [L"公共偏置"] = {
                   [L"CHN"] = L"公共偏置",
                   [L"POL"] = L"Wspolne odsuniecie",
                   [L"ENG"] = L"PublicOffset",},

    [L"2.加工深度"] = {
                   [L"CHN"] = L"2.加工深度",
                   [L"POL"] = L"2.Glebokosc Przetw.",
                   [L"ENG"] = L"2.Process Depth",},

    [L"4.加工深度"] = {
                   [L"CHN"] = L"4.加工深度",
                   [L"POL"] = L"4.Gleb. Przetw.",
                   [L"ENG"] = L"4.Process Depth",},

    [L"%s软限位"] = {
                   [L"CHN"] = L"%s软限位",
                   [L"POL"] = L"%sLimit Progr.",
                   [L"ENG"] = L"%sSoft Limit",},

    [L"是否使用S 型算法加减速"] = {
                   [L"CHN"] = L"是否使用S 型算法加减速",
                   [L"POL"] = L"Uzyj algorytmu S",
                   [L"ENG"] = L"Use S TypeAlgorithm",},

    [L"确定删除日志文件?"] = {
                   [L"CHN"] = L"确定删除日志文件?",
                   [L"POL"] = L"Napewno usunac plik dziennika?",
                   [L"ENG"] = L"Sure To Del-ete Log File?",},

    [L"轴停"] = {
                   [L"CHN"] = L"轴停",
                   [L"POL"] = L"Wyl Wrzec",
                   [L"ENG"] = L"SOff",},

    [L"10. 停止主轴"] = {
                   [L"CHN"] = L"10. 停止主轴",
                   [L"POL"] = L"10.Zatrzym Wrzec.",
                   [L"ENG"] = L"10.SpindleStop",},

    [L"将要生成的阵列文件已存在，是否覆盖？"] = {
                   [L"CHN"] = L"将要生成的阵列文件已存在，是否覆盖？",
                   [L"POL"] = L"Zastepowanie\npliku juz obecnego",
                   [L"ENG"] = L"File is\nexisting，tooverwrite？",},

    [L"* 反向间隙"] = {
                   [L"CHN"] = L"* 反向间隙",
                   [L"POL"] = L"* Luz",
                   [L"ENG"] = L"* Backlash ",},

    [L"1.刀具直径"] = {
                   [L"CHN"] = L"1.刀具直径",
                   [L"POL"] = L"1.Srednica Narz.",
                   [L"ENG"] = L"1.Tool Diameter",},

    [L"导入成功, 是否立即重启?"] = {
                   [L"CHN"] = L"导入成功, 是否立即重启?",
                   [L"POL"] = L" Zaimportowano! Zrestartowac?",
                   [L"ENG"] = L" Imported!   Restart?",},

    [L"8.诊断"] = {
                   [L"CHN"] = L"8.诊断",
                   [L"POL"] = L"8.Diagnostyka",
                   [L"ENG"] = L"8.Diagnosis",},

    [L"手速"] = {
                   [L"CHN"] = L"手速",
                   [L"POL"] = L"Predkosc Reczna",
                   [L"ENG"] = L"MSpd",},

    [L"15. 换刀参数"] = {
                   [L"CHN"] = L"15. 换刀参数",
                   [L"POL"] = L"15.Wymiana Narz.",
                   [L"ENG"] = L"15.Tool Change",},

    [L"紧停后是否取消回原点标志"] = {
                   [L"CHN"] = L"紧停后是否取消回原点标志",
                   [L"POL"] = L"Anuluj znak baz. po E-Stopie",
                   [L"ENG"] = L"Cancel REFSign Aft E-stop",},

    [L"确认删除工件原点？"] = {
                   [L"CHN"] = L"确认删除工件原点？",
                   [L"POL"] = L"Sure to delete origin？",
                   [L"ENG"] = L"Sure to delete origin？",},

    [L"确定"] = {
                   [L"CHN"] = L"确定",
                   [L"POL"] = L"OK",
                   [L"ENG"] = L"OK",},

    [L"3.G56 工件偏置"] = {
                   [L"CHN"] = L"3.G56 工件偏置",
                   [L"POL"] = L"3.Odsuniecie G56",
                   [L"ENG"] = L"3.G56 Offset",},

    [L"* 暂停时抬刀量"] = {
                   [L"CHN"] = L"* 暂停时抬刀量",
                   [L"POL"] = L"* Wysokosc podniesienia przy pauzie",
                   [L"ENG"] = L"* lifting height at pause",},

    [L"开启换刀提示"] = {
                   [L"CHN"] = L"开启换刀提示",
                   [L"POL"] = L" Wlacz podpowiedz wymiany narzedzia",
                   [L"ENG"] = L" Enable   Tool Change Tip",},

    [L"  1   关闭系统"] = {
                   [L"CHN"] = L"  1   关闭系统",
                   [L"POL"] = L"  1   Wylacz",
                   [L"ENG"] = L"  1   Shutdown",},

    [L"OK: 选择      0:在本地和U 盘间切换"] = {
                   [L"CHN"] = L"OK: 选择      0:在本地和U 盘间切换",
                   [L"POL"] = L"OK:Select       0:Switch between U-disk and Local",
                   [L"ENG"] = L"OK:Select       0:Switch between U-disk and Local",},

    [L"6.公制尺寸"] = {
                   [L"CHN"] = L"6.公制尺寸",
                   [L"POL"] = L"6.Uklad metryczny",
                   [L"ENG"] = L"6.Metric Size",},

    [L"换刀上位"] = {
                   [L"CHN"] = L"换刀上位",
                   [L"POL"] = L"Pozycja Wycinania",
                   [L"ENG"] = L"Cut Up Po-sition",},

    [L"回指定停车位置"] = {
                   [L"CHN"] = L"回指定停车位置",
                   [L"POL"] = L"Do miejsca parkowania",
                   [L"ENG"] = L"To park site",},

    [L"文件加载进度"] = {
                   [L"CHN"] = L"文件加载进度",
                   [L"POL"] = L"Wczytywanie w trakcie",
                   [L"ENG"] = L"Loading Progress",},

    [L"暂停无效"] = {
                   [L"CHN"] = L"暂停无效",
                   [L"POL"] = L"Niepoprawna pauza!",
                   [L"ENG"] = L"Invalid     pause!",},

    [L"* G0使用100%进给倍率"] = {
                   [L"CHN"] = L"* G0使用100%进给倍率",
                   [L"POL"] = L"*100% Posuwu dla G00",
                   [L"ENG"] = L"*100% FeedFor G00",},

    [L"3. Z轴回退距离"] = {
                   [L"CHN"] = L"3. Z轴回退距离",
                   [L"POL"] = L"3.Odsuniecie osi Z",
                   [L"ENG"] = L"3.Z Retract Dist",},

    [L"文件生成进度"] = {
                   [L"CHN"] = L"文件生成进度",
                   [L"POL"] = L"Postep",
                   [L"ENG"] = L"Generate Progress",},

    [L"该文件已经加载,是否删除?"] = {
                   [L"CHN"] = L"该文件已经加载,是否删除?",
                   [L"POL"] = L"Plik zostal wczytany, czy chcesz go usunac ?",
                   [L"ENG"] = L"The file is loaded, do you want to delete it?",},

    [L"起跳速度"] = {
                   [L"CHN"] = L"起跳速度",
                   [L"POL"] = L"Predk. Skoku",
                   [L"ENG"] = L"Jump Speed",},

    [L"加工时间：  %s!"] = {
                   [L"CHN"] = L"加工时间：  %s!",
                   [L"POL"] = L"Process Time:%s！",
                   [L"ENG"] = L"Process Time:%s！",},

    [L"5.偏置设置"] = {
                   [L"CHN"] = L"5.偏置设置",
                   [L"POL"] = L"5.Odsuniecie",
                   [L"ENG"] = L"5.Offset",},

    [L"确定恢复备份参数?"] = {
                   [L"CHN"] = L"确定恢复备份参数?",
                   [L"POL"] = L"Napewno przywrocic Kopie Zapasowa?",
                   [L"ENG"] = L"Sure To Res-tore Backup?",},

    [L"低速"] = {
                   [L"CHN"] = L"低速",
                   [L"POL"] = L"Wolno ",
                   [L"ENG"] = L"Slow ",},

    [L"1.输入停车位置"] = {
                   [L"CHN"] = L"1.输入停车位置",
                   [L"POL"] = L"1.Wprowadz miejsce",
                   [L"ENG"] = L"1.Input Site",},

    [L"加工速度"] = {
                   [L"CHN"] = L"加工速度",
                   [L"POL"] = L"Predkosc Gxx",
                   [L"ENG"] = L"Gxx speed",},

    [L"确认读取工件原点？"] = {
                   [L"CHN"] = L"确认读取工件原点？",
                   [L"POL"] = L"Sure to load origin?",
                   [L"ENG"] = L"Sure to load origin?",},

    [L"当前操作存在危险, 建议先回Z轴,是否继续？"] = {
                   [L"CHN"] = L"当前操作存在危险, 建议先回Z轴,是否继续？",
                   [L"POL"] = L"Niebezpieczna operacja, najpierw bazuj os Z, kontynuowac?",
                   [L"ENG"] = L"Dangerous   operation,  Had better  home Z first,continue?",},

    [L"注册失败, 请联系厂家"] = {
                   [L"CHN"] = L"注册失败, 请联系厂家",
                   [L"POL"] = L"Nieudana rejestracja!Skontaktuj sie z producentem!",
                   [L"ENG"] = L"Failed to   register!co-ntact the   manufacturer!",},

    [L"* 轴输出方向"] = {
                   [L"CHN"] = L"* 轴输出方向",
                   [L"POL"] = L"*Kierunek Wyj. Osi",
                   [L"ENG"] = L"*Axis OutputDir",},

    [L"8.短线段限速长度"] = {
                   [L"CHN"] = L"8.短线段限速长度",
                   [L"POL"] = L"8.Dlugosc limitu predkosci",
                   [L"ENG"] = L"8.SpdLmt Length",},

    [L"1.一般模式"] = {
                   [L"CHN"] = L"1.一般模式",
                   [L"POL"] = L"1.Typ Ogolny",
                   [L"ENG"] = L"1.General Type",},

    [L"请选择一个加工文件!"] = {
                   [L"CHN"] = L"请选择一个加工文件!",
                   [L"POL"] = L"Wybierz jeden plik!",
                   [L"ENG"] = L"Select one  file!",},

    [L"3.系统升级"] = {
                   [L"CHN"] = L"3.系统升级",
                   [L"POL"] = L"3.Aktualizacja systemu",
                   [L"ENG"] = L"3.System Update",},

    [L"宽度"] = {
                   [L"CHN"] = L"宽度",
                   [L"POL"] = L"Szerokosc",
                   [L"ENG"] = L"Width   ",},

    [L"旋转轴加速度"] = {
                   [L"CHN"] = L"旋转轴加速度",
                   [L"POL"] = L" Przysp.Rotary Y Acceleration",
                   [L"ENG"] = L" Rotary Y Acceleration",},

    [L"3.加工结束停主轴"] = {
                   [L"CHN"] = L"3.加工结束停主轴",
                   [L"POL"] = L"3.Wyl. Wrzec. na Koncu",
                   [L"ENG"] = L"3.SOff at End",},

    [L"|T|输入地址为无效物理地址!"] = {
                   [L"CHN"] = L"|T|输入地址为无效物理地址!",
                   [L"POL"] = L"|T|Zostal wprowadzony niewlasciwy adres!",
                   [L"ENG"] = L"|T|It is invalid physical address entered!",},

    [L"4.机床行程"] = {
                   [L"CHN"] = L"4.机床行程",
                   [L"POL"] = L"4.Skok Maszyny",
                   [L"ENG"] = L"4.MachineStrok",},

    [L"10. 换刀后对刀"] = {
                   [L"CHN"] = L"10. 换刀后对刀",
                   [L"POL"] = L"10.Calibrate Tool",
                   [L"ENG"] = L"10.Calibrate Tool",},

    [L"延时"] = {
                   [L"CHN"] = L"延时",
                   [L"POL"] = L"Opoznienie",
                   [L"ENG"] = L"Delay",},

    [L"2.Plt 单位"] = {
                   [L"CHN"] = L"2.Plt 单位",
                   [L"POL"] = L"2.Jednostka Plt",
                   [L"ENG"] = L"2.Plt Unit",},

    [L":切换至上或下一个端口  Shift:更改当前端口值        OK: 按一下保存, 否则不保存"] = {
                   [L"CHN"] = L":切换至上或下一个端口  Shift:更改当前端口值        OK: 按一下保存, 否则不保存",
                   [L"POL"] = L":przesun do ostatniego lub nastepnego portu Shift: zmiana aktualnej wartosci portu    OK: nacisnij OK aby zapisac zmiany.",
                   [L"ENG"] = L":shift tothe last or   the next port Shift: change the current   port value    OK:pressing OKwill save the changed value,or it will notbe saved.",},

    [L"未生成代码!"] = {
                   [L"CHN"] = L"未生成代码!",
                   [L"POL"] = L"Kod nie zostal wygenerowany!",
                   [L"ENG"] = L"No Code Is  Generated!",},

    [L"4.形状独立加工"] = {
                   [L"CHN"] = L"4.形状独立加工",
                   [L"POL"] = L"4.Obrobka ksztaltu",
                   [L"ENG"] = L"4.Shape Process",},

    [L"* 安全高度"] = {
                   [L"CHN"] = L"* 安全高度",
                   [L"POL"] = L"* Bezpieczna wysokosc",
                   [L"ENG"] = L"* Safety  Height",},

    [L"不能小于0!"] = {
                   [L"CHN"] = L"不能小于0!",
                   [L"POL"] = L"    nie moze byc mniej niz 0!  ",
                   [L"ENG"] = L"    can not be  less than 0!  ",},

    [L"确认要拷贝文件?"] = {
                   [L"CHN"] = L"确认要拷贝文件?",
                   [L"POL"] = L"Sure to copythe file?",
                   [L"ENG"] = L"Sure to copythe file?",},

    [L"使用mm作单位"] = {
                   [L"CHN"] = L"使用mm作单位",
                   [L"POL"] = L"Uzyc mm jako jedn.",
                   [L"ENG"] = L"Use mm As Unit",},

    [L"0:不处理1:曲线2:圆弧"] = {
                   [L"CHN"] = L"0:不处理1:曲线2:圆弧",
                   [L"POL"] = L"0: Not;1: Curve Smooth;3: Arc Smooth",
                   [L"ENG"] = L"0: Not;1: Curve Smooth;3: Arc Smooth",},

    [L"16. G0进给100%"] = {
                   [L"CHN"] = L"16. G0进给100%",
                   [L"POL"] = L"16G00 Posuw 100%",
                   [L"ENG"] = L"16G00 Feed 100%",},

    [L"4.最大转弯加速度"] = {
                   [L"CHN"] = L"4.最大转弯加速度",
                   [L"POL"] = L"4.Maks. Przysp. Obr.",
                   [L"ENG"] = L"4.Max.Turn Acc.",},

    [L"步 Z"] = {
                   [L"CHN"] = L"步 Z",
                   [L"POL"] = L"Krok Z",
                   [L"ENG"] = L"StepZ",},

    [L"刀具直径磨损量"] = {
                   [L"CHN"] = L"刀具直径磨损量",
                   [L"POL"] = L"Zuzycie srednicy narzedzia",
                   [L"ENG"] = L"Tool diam-eter wear extent",},

    [L"按键配置文件格式有错!"] = {
                   [L"CHN"] = L"按键配置文件格式有错!",
                   [L"POL"] = L"There is a problem with the format of key configuration file!",
                   [L"ENG"] = L"There is a problem with the format of key configuration file!",},

    [L"  值："] = {
                   [L"CHN"] = L"  值：",
                   [L"POL"] = L"Wartosc:",
                   [L"ENG"] = L"Value:",},

    [L"圆弧增量模式是否有效"] = {
                   [L"CHN"] = L"圆弧增量模式是否有效",
                   [L"POL"] = L"  Wlacz tryb przyrostowy",
                   [L"ENG"] = L"  Enable  Incremental Mode",},

    [L"高度"] = {
                   [L"CHN"] = L"高度",
                   [L"POL"] = L"Wysokosc  ",
                   [L"ENG"] = L"Height  ",},

    [L"!请手动退出限位。"] = {
                   [L"CHN"] = L"!请手动退出限位。",
                   [L"POL"] = L"Limit! Exit manually.",
                   [L"ENG"] = L"Limit! Exit manually.",},

    [L"请输入停车位置"] = {
                   [L"CHN"] = L"请输入停车位置",
                   [L"POL"] = L"Wprowadz miejsce parkowania",
                   [L"ENG"] = L"Input park site",},

    [L"间隔时停主轴"] = {
                   [L"CHN"] = L"间隔时停主轴",
                   [L"POL"] = L"Interwal Wyl. Wrzec.",
                   [L"ENG"] = L" SPDL Off In The Interval",},

    [L"2.Z 轴回原点"] = {
                   [L"CHN"] = L"2.Z 轴回原点",
                   [L"POL"] = L"2.Bazowanie Z",
                   [L"ENG"] = L"2.Z Home",},

    [L"是否进行XY轴坐标清零？"] = {
                   [L"CHN"] = L"是否进行XY轴坐标清零？",
                   [L"POL"] = L"Clear XY      coordinate?",
                   [L"ENG"] = L"Clear XY      coordinate?",},

    [L"系统忙"] = {
                   [L"CHN"] = L"系统忙",
                   [L"POL"] = L"System przetwarza!",
                   [L"ENG"] = L"System is Busy!",},

    [L"* 空程移动时抬刀高度"] = {
                   [L"CHN"] = L"* 空程移动时抬刀高度",
                   [L"POL"] = L"* Wysokosc podnoszenia przy G00",
                   [L"ENG"] = L"* Lifting Height At G00",},

    [L"  1:一般, 2:求交, 3:插入"] = {
                   [L"CHN"] = L"  1:一般, 2:求交, 3:插入",
                   [L"POL"] = L"1:Gen.,2:Przeciecie,3:Wstawienie",
                   [L"ENG"] = L"1:Gen.,2:Intersect,3:Insrt",},

    [L"OK: 选取一个或多个文件，再按则取消选中状态1:载入，只能选取一个加工文件2:删除        3:拷贝，U 盘<-->本地\n注：文件夹不支持载入，删除，拷贝操作"] = {
                   [L"CHN"] = L"OK: 选取一个或多个文件，再按则取消选中状态1:载入，只能选取一个加工文件2:删除        3:拷贝，U 盘<-->本地\n注：文件夹不支持载入，删除，拷贝操作",
                   [L"POL"] = L"OK: Wybierz plik(i); naciskajac ponownie anulujesz wybor ①:Wczytaj; tylko jeden plik na raz      \
②:Usun     ③:Przenies pliki pomiedzy dyskiem USB i dyskiem lokalnym\n\nSkrot: Wc:Wczytaj\nUs:Usun",
                   [L"ENG"] = L"OK: Select a  file(s); pres-sing it again will cancel   the checked   state         ①:Load; only one machining file can be   selected      \
②:Delete     ③:Transfer   files between U-disk and    Local\nNOTICE:Folder does not\nsupport load, delete,copy\noperation\n\nAbbreviation: Ld:Load\nde:delete",},

    [L"1.软件版本"] = {
                   [L"CHN"] = L"1.软件版本",
                   [L"POL"] = L"1.Wersja oprogram.",
                   [L"ENG"] = L"1.Software Ver.",},

    [L"对刀仪厚度"] = {
                   [L"CHN"] = L"对刀仪厚度",
                   [L"POL"] = L"Grubosc Plytki Kalibr.",
                   [L"ENG"] = L"CalibratorThickness",},

    [L"|M|按键配置文件格式有错!"] = {
                   [L"CHN"] = L"|M|按键配置文件格式有错!",
                   [L"POL"] = L"|M|There is a problem with the format of key configuration file!",
                   [L"ENG"] = L"|M|There is a problem with the format of key configuration file!",},

    [L"请按下一个键"] = {
                   [L"CHN"] = L"请按下一个键",
                   [L"POL"] = L"Nacisnij klawisz:",
                   [L"ENG"] = L"Press a key:",},

    [L"帮助弹出延时设置错误"] = {
                   [L"CHN"] = L"帮助弹出延时设置错误",
                   [L"POL"] = L"Blad Opoznienia wyswietlania pomocy",
                   [L"ENG"] = L"Help MessageShow Delay  Error",},

    [L"4.输入端口检测"] = {
                   [L"CHN"] = L"4.输入端口检测",
                   [L"POL"] = L"4.Diagnostyka Port. Wej.",
                   [L"ENG"] = L"4.Inport Diag",},

    [L"雕刻深度"] = {
                   [L"CHN"] = L"雕刻深度",
                   [L"POL"] = L"Glebokosc Obrobki",
                   [L"ENG"] = L"EngrDpth",},

    [L"4.主轴最大转速"] = {
                   [L"CHN"] = L"4.主轴最大转速",
                   [L"POL"] = L"4.Maks. Predkosc Wrzeciona",
                   [L"ENG"] = L"4.Max.Spdl Speed",},

    [L"是否需要重启系统?"] = {
                   [L"CHN"] = L"是否需要重启系统?",
                   [L"POL"] = L"Czy napewno zrestartowac?",
                   [L"ENG"] = L"Sure To Reb-oot System?",},

    [L"系统检测到上次非正常退出，是否继续加工?"] = {
                   [L"CHN"] = L"系统检测到上次非正常退出，是否继续加工?",
                   [L"POL"] = L"Ostatnie wylaczenie bylo nieprawidlowe,  kontynuowac?",
                   [L"ENG"] = L"Last quit isimproper,   continue to process?",},

    [L"4.刀具长度磨损量"] = {
                   [L"CHN"] = L"4.刀具长度磨损量",
                   [L"POL"] = L"4.Zuzycie Dlugosci Narzedzia",
                   [L"ENG"] = L"4.ToolLenWear",},

    [L"8.原点列表"] = {
                   [L"CHN"] = L"8.原点列表",
                   [L"POL"] = L"8.Origin List",
                   [L"ENG"] = L"8.Origin List",},

    [L"6.循环加工设置"] = {
                   [L"CHN"] = L"6.循环加工设置",
                   [L"POL"] = L"6.Cykl Przetwarzania",
                   [L"ENG"] = L"6.CycleProcess",},

    [L"1.刀补有效"] = {
                   [L"CHN"] = L"1.刀补有效",
                   [L"POL"] = L"1.Wlacz Komp. Narz.",
                   [L"ENG"] = L"1.ToolCompEnable",},

    [L"2.主轴启停延时"] = {
                   [L"CHN"] = L"2.主轴启停延时",
                   [L"POL"] = L"2.Opoznienie Wl/Wyl",
                   [L"ENG"] = L"2.ON/OFF Delay",},

    [L"读取系统可用存储空间失败!"] = {
                   [L"CHN"] = L"读取系统可用存储空间失败!",
                   [L"POL"] = L"NIeudana proba uzyskania dostepu do wolnej przestrzeni dyskowej!",
                   [L"ENG"] = L"Fail to get disk free space!",},

    [L"3.X 轴回原点"] = {
                   [L"CHN"] = L"3.X 轴回原点",
                   [L"POL"] = L"3.Bazowanie X",
                   [L"ENG"] = L"3.X Home",},

    [L"回固定点失败"] = {
                   [L"CHN"] = L"回固定点失败",
                   [L"POL"] = L"Fail back to fixed!",
                   [L"ENG"] = L"Fail back to fixed!",},

    [L"4.导出参数"] = {
                   [L"CHN"] = L"4.导出参数",
                   [L"POL"] = L"4.Parametry Eksportu",
                   [L"ENG"] = L"4.Export Params",},

    [L"最大转弯加速度"] = {
                   [L"CHN"] = L"最大转弯加速度",
                   [L"POL"] = L"Maks. Przysp. Obr.",
                   [L"ENG"] = L"Max. Turn Acc.",},

    [L"接近速度"] = {
                   [L"CHN"] = L"接近速度",
                   [L"POL"] = L" Predkosc Dojazdu",
                   [L"ENG"] = L" Approach Speed",},

    [L"总行:"] = {
                   [L"CHN"] = L"总行:",
                   [L"POL"] = L"Total:",
                   [L"ENG"] = L"Total:",},

    [L"未选择文件！"] = {
                   [L"CHN"] = L"未选择文件！",
                   [L"POL"] = L"Nie wybrano\nPliku!",
                   [L"ENG"] = L"No Select\nFile!",},

    [L"未找到文件, 切换到U 盘?"] = {
                   [L"CHN"] = L"未找到文件, 切换到U 盘?",
                   [L"POL"] = L"Plik nieodnaleziony, Pokazac Plik Usb?",
                   [L"ENG"] = L"File Not found, Show Usb File?",},

    [L"文件大于5M，不能阵列！"] = {
                   [L"CHN"] = L"文件大于5M，不能阵列！",
                   [L"POL"] = L"Plik wiekszy niz 5M nie jest\nobslugiwany!",
                   [L"ENG"] = L"The file is big than 5M,not be\nsupported!",},

    [L"* 行程下限"] = {
                   [L"CHN"] = L"* 行程下限",
                   [L"POL"] = L"Dolny Limit Skoku",
                   [L"ENG"] = L"StrkLowerLmt",},

    [L"行号:"] = {
                   [L"CHN"] = L"行号:",
                   [L"POL"] = L"Line:",
                   [L"ENG"] = L"Line:",},

    [L"12. 前瞻程序段数"] = {
                   [L"CHN"] = L"12. 前瞻程序段数",
                   [L"POL"] = L"12Podglad Nast Linii",
                   [L"ENG"] = L"12ForwardlookSeg",},

    [L"4.Y 轴回原点"] = {
                   [L"CHN"] = L"4.Y 轴回原点",
                   [L"POL"] = L"4.Bazowanie Y",
                   [L"ENG"] = L"4.Y Home",},

    [L"1.加工参数设置"] = {
                   [L"CHN"] = L"1.加工参数设置",
                   [L"POL"] = L"1.Ustawienie Parametrow",
                   [L"ENG"] = L"1.Params Setting",},

    [L"刀具直径"] = {
                   [L"CHN"] = L"刀具直径",
                   [L"POL"] = L"Srednica Narz.",
                   [L"ENG"] = L"Tool Diam-eter",},

    [L"刀具偏置 %d"] = {
                   [L"CHN"] = L"刀具偏置 %d",
                   [L"POL"] = L"Odsuniecie Narzedzia %d",
                   [L"ENG"] = L"Tool Offset %d",},

    [L"* 主轴档位数"] = {
                   [L"CHN"] = L"* 主轴档位数",
                   [L"POL"] = L"* Biegi Wrzeciona",
                   [L"ENG"] = L"* Spindle Gears",},

    [L"6.选刀加工"] = {
                   [L"CHN"] = L"6.选刀加工",
                   [L"POL"] = L"6.Wybierz Nr narz.",
                   [L"ENG"] = L"6.Select ToolNo.",},

    [L"3.回退距离"] = {
                   [L"CHN"] = L"3.回退距离",
                   [L"POL"] = L"3.Odleglosc powrotu",
                   [L"ENG"] = L"3.Retract Dist",},

    [L"主轴延时时间"] = {
                   [L"CHN"] = L"主轴延时时间",
                   [L"POL"] = L"  Opoznienie Wl/WYl Wrzeciona",
                   [L"ENG"] = L"  Spindle ON/OFF Delay",},

    [L"Z:"] = {
                   [L"CHN"] = L"Z:",
                   [L"POL"] = L"Z:",
                   [L"ENG"] = L"Z:",},

    [L"* 主轴初始档位"] = {
                   [L"CHN"] = L"* 主轴初始档位",
                   [L"POL"] = L"* Pocz. Bieg Wrzeciona",
                   [L"ENG"] = L"* Spindle Initial Gear",},

    [L"13.Eng文件参数"] = {
                   [L"CHN"] = L"13.Eng文件参数",
                   [L"POL"] = L"13.Parametry Eng",
                   [L"ENG"] = L"13.Eng Params",},

    [L"快捷键:\n"] = {
                   [L"CHN"] = L"快捷键:\n",
                   [L"POL"] = L"Shortcut keys:",
                   [L"ENG"] = L"Shortcut keys:",},
                   
    [L"刀具长度磨损量"] = {
                   [L"CHN"] = L"刀具长度磨损量",
                   [L"POL"] = L"dlugosc zuzycia narzedzia",
                   [L"ENG"] = L"tool leng-th wear extent",},

    [L"X:"] = {
                   [L"CHN"] = L"X:",
                   [L"POL"] = L"X:",
                   [L"ENG"] = L"X:",},

    [L"未找到加工文件!"] = {
                   [L"CHN"] = L"未找到加工文件!",
                   [L"POL"] = L"Pliku nie odnaleziono!",
                   [L"ENG"] = L"Process filenot found!",},

    [L"Z 向下刀速度"] = {
                   [L"CHN"] = L"Z 向下刀速度",
                   [L"POL"] = L"Predkosc Opuszczania Z",
                   [L"ENG"] = L"Plunge SpdAlong Z",},

    [L"加加速度"] = {
                   [L"CHN"] = L"加加速度",
                   [L"POL"] = L"Zmien stopien Przysp. Poj. Osi.",
                   [L"ENG"] = L"ChangerateOf Sgl Axis Acc.",},
                   
                   
    [L"对刀"] = {
                   [L"CHN"] = L"对刀",
                   [L"POL"] = L"Kalibr. Narz.",
                   [L"ENG"] = L"ToolCali",},
                   
    [L"刀具补偿有效"] = {
                   [L"CHN"] = L"刀具补偿有效",
                   [L"POL"] = L"Wlacz Komp. Narz.",
                   [L"ENG"] = L"Enable to-ol compensation",},

    [L"固定对刀块X 机械坐标"] = {
                   [L"CHN"] = L"固定对刀块X 机械坐标",
                   [L"POL"] = L"Wsp. Masz. X plytki kalibr.",
                   [L"ENG"] = L"X MEC Coor of Cali block",},

    [L"短线段限速有效"] = {
                   [L"CHN"] = L"短线段限速有效",
                   [L"POL"] = L" Wlacz Limit Predk. Krotkich Segm.",
                   [L"ENG"] = L" Enable   Short Seg.SpdLmt",},

    [L"* 底部加工有效"] = {
                   [L"CHN"] = L"* 底部加工有效",
                   [L"POL"] = L"* Wlacz Obrobke Dna",
                   [L"ENG"] = L"* Enable  Bottom Machining",},

    [L"端口配置文件内容有错,请检查配置文件!"] = {
                   [L"CHN"] = L"端口配置文件内容有错,请检查配置文件!",
                   [L"POL"] = L"Zawartosc pliku konfiguracji jest nieprawidlowa, prosze sprawdz plik!",
                   [L"ENG"] = L"Port configuration file content is incorrect, please check the file!",},

    [L"前瞻程序段数"] = {
                   [L"CHN"] = L"前瞻程序段数",
                   [L"POL"] = L"Segmenty",
                   [L"ENG"] = L"Prospect. Segments",},

    [L"1.补偿使能"] = {
                   [L"CHN"] = L"1.补偿使能",
                   [L"POL"] = L"1.Kompensacja Wl.",
                   [L"ENG"] = L"1.CompensationON",},

    [L"当前状态不能选择加工!"] = {
                   [L"CHN"] = L"当前状态不能选择加工!",
                   [L"POL"] = L"Unable to\nsenior start\ncurrent sta-te!",
                   [L"ENG"] = L"Unable to\nsenior start\ncurrent sta-te!",},

    [L"未选择原点!"] = {
                   [L"CHN"] = L"未选择原点!",
                   [L"POL"] = L"No select origin!",
                   [L"ENG"] = L"No select origin!",},

    [L"2.加工次数"] = {
                   [L"CHN"] = L"2.加工次数",
                   [L"POL"] = L"2.Liczba cykli",
                   [L"ENG"] = L"2.Cycle Times",},

    [L"回原点中"] = {
                   [L"CHN"] = L"回原点中",
                   [L"POL"] = L"Bazowanie",
                   [L"ENG"] = L"Homing",},

    [L"没有文件或文件为空! "] = {
                   [L"CHN"] = L"没有文件或文件为空! ",
                   [L"POL"] = L"Plik nie zostal wczytany lub Plik pusty!",
                   [L"ENG"] = L"No File Loa-ded Or File Is Empty!",},

    [L"G57 工件偏置"] = {
                   [L"CHN"] = L"G57 工件偏置",
                   [L"POL"] = L"Odsuniecie G57",
                   [L"ENG"] = L"G57 Offset",},

    [L"12.Dxf文件参数"] = {
                   [L"CHN"] = L"12.Dxf文件参数",
                   [L"POL"] = L"12.Parametry Dxf",
                   [L"ENG"] = L"12.Dxf Params",},

    [L"系统已到期!"] = {
                   [L"CHN"] = L"系统已到期!",
                   [L"POL"] = L"Waznosc Systemu wygasla",
                   [L"ENG"] = L"System's expired",},

    [L"文件拷贝进度"] = {
                   [L"CHN"] = L"文件拷贝进度",
                   [L"POL"] = L"Postep kopiowania",
                   [L"ENG"] = L"Copy Progress",},

    [L"正在识别 U盘，请等待。。。"] = {
                   [L"CHN"] = L"正在识别 U盘，请等待。。。",
                   [L"POL"] = L"Identyfikowanie dysku USB..",
                   [L"ENG"] = L"Identifying the USB flash disk..",},

    [L"当前状态不能执行该操作!"] = {
                   [L"CHN"] = L"当前状态不能执行该操作!",
                   [L"POL"] = L"Invalid\noperate！",
                   [L"ENG"] = L"Invalid\noperate！",},

    [L"确定恢复出厂参数?"] = {
                   [L"CHN"] = L"确定恢复出厂参数?",
                   [L"POL"] = L"Przywrocic parametry fabryczne?",
                   [L"ENG"] = L"Restore Fac-tory params?",},

    [L"确认要删除文件?"] = {
                   [L"CHN"] = L"确认要删除文件?",
                   [L"POL"] = L"Napewno usunac plik?",
                   [L"ENG"] = L"Sure to del-ete the file?",},

    [L""] = {
                   [L"CHN"] = L"",
                   [L"POL"] = L"",
                   [L"ENG"] = L"",},

    [L"设置成功，是否立即重启?"] = {
                   [L"CHN"] = L"设置成功，是否立即重启?",
                   [L"POL"] = L"Zrestartowac?",
                   [L"ENG"] = L"Successfully!Reboot Now?",},

    [L"执行测量刀具长度操作？"] = {
                   [L"CHN"] = L"执行测量刀具长度操作？",
                   [L"POL"] = L"Wykonac pomiar dlugosci narzedzia, Kontynuowac?",
                   [L"ENG"] = L"To perform Measure toollength,    Continue?",},

    [L"屏蔽S 指令"] = {
                   [L"CHN"] = L"屏蔽S 指令",
                   [L"POL"] = L"Ignoruj kod S",
                   [L"ENG"] = L" Ignore S Code",},

    [L"列数"] = {
                   [L"CHN"] = L"列数",
                   [L"POL"] = L"Kolumny",
                   [L"ENG"] = L"Columns",},

    [L"G73_G83 退刀量"] = {
                   [L"CHN"] = L"G73_G83 退刀量",
                   [L"POL"] = L" Odleglosc Odsuniecia G73_G83",
                   [L"ENG"] = L" G73_G83  Retract Distance",},

    [L"12. 参考圆速度"] = {
                   [L"CHN"] = L"12. 参考圆速度",
                   [L"POL"] = L"12Predk. Okregu Wzorc.",
                   [L"ENG"] = L"12Ref Cir. Speed",},

    [L"3.选择加工"] = {
                   [L"CHN"] = L"3.选择加工",
                   [L"POL"] = L"3.Wybierz linie nr",
                   [L"ENG"] = L"3.Select Line No",},

    [L"7.G73_G83 退刀量"] = {
                   [L"CHN"] = L"7.G73_G83 退刀量",
                   [L"POL"] = L"7.G73_G83Wycofanie",
                   [L"ENG"] = L"7.G73_G83Retract",},

    [L"系统将进行循环加工，循环次数%d"] = {
                   [L"CHN"] = L"系统将进行循环加工，循环次数%d",
                   [L"POL"] = L"Cykl zostanie rozpoczety,liczba cykli:%d",
                   [L"ENG"] = L"Cycle       process willbegin,cycle times:%d",},

    [L"生成文件成功!"] = {
                   [L"CHN"] = L"生成文件成功!",
                   [L"POL"] = L"Generowanie\nkodu\npomyslne!",
                   [L"ENG"] = L"Generate\ncode\nsuccessfully!",},

    [L"请先卸载文件!"] = {
                   [L"CHN"] = L"请先卸载文件!",
                   [L"POL"] = L"Prosze o usuniecie pliku z pamieci!",
                   [L"ENG"] = L"Please unload   the file first!",},

    [L"G56 工件偏置"] = {
                   [L"CHN"] = L"G56 工件偏置",
                   [L"POL"] = L"Odsuniecie G56",
                   [L"ENG"] = L"G56 Offset",},

    [L"不需要切换语言!"] = {
                   [L"CHN"] = L"不需要切换语言!",
                   [L"POL"] = L"Nie ma potrzeby przelaczania jezyka!",
                   [L"ENG"] = L"No Need To  Switch Lang-uage!",},

    [L"取消"] = {
                   [L"CHN"] = L"取消",
                   [L"POL"] = L"ESC",
                   [L"ENG"] = L"ESC",},

    [L"* 刀间距"] = {
                   [L"CHN"] = L"* 刀间距",
                   [L"POL"] = L"* Krok Narz.",
                   [L"ENG"] = L"* Tool step",},

    [L"规划前瞻距离"] = {
                   [L"CHN"] = L"规划前瞻距离",
                   [L"POL"] = L"Look Ahead Distance",
                   [L"ENG"] = L"Look Ahead Distance",},

    [L"行数"] = {
                   [L"CHN"] = L"行数",
                   [L"POL"] = L"Wiersze",
                   [L"ENG"] = L"Rows",},

    [L"* Plt 单位"] = {
                   [L"CHN"] = L"* Plt 单位",
                   [L"POL"] = L"* Jednostka Plt",
                   [L"ENG"] = L"* Plt Unit",},

    [L"1.停车方式 "] = {
                   [L"CHN"] = L"1.停车方式 ",
                   [L"POL"] = L"1.Tryb Parkowania",
                   [L"ENG"] = L"1.Park Mode",},

    [L"回工件坐标原点"] = {
                   [L"CHN"] = L"回工件坐标原点",
                   [L"POL"] = L"Do punktu zerowego WCS",
                   [L"ENG"] = L"To WCS Origin",},

    [L"Z 正限位"] = {
                   [L"CHN"] = L"Z 正限位",
                   [L"POL"] = L"limit +Z",
                   [L"ENG"] = L"Z +Limit",},

    [L"5.机械原点设置"] = {
                   [L"CHN"] = L"5.机械原点设置",
                   [L"POL"] = L"5.Ustawienie punktu bazowego",
                   [L"ENG"] = L"5.REF.PointSet",},

    [L"11. 回换刀前位置"] = {
                   [L"CHN"] = L"11. 回换刀前位置",
                   [L"POL"] = L"11.Powrot do Poz. Pocz.",
                   [L"ENG"] = L"11.Back Pre_Pos",},

    [L"刀具位置 %d"] = {
                   [L"CHN"] = L"刀具位置 %d",
                   [L"POL"] = L"Pozycja Narzedzia %d",
                   [L"ENG"] = L"Tool Position %d",},

    [L"无效模式"] = {
                   [L"CHN"] = L"无效模式",
                   [L"POL"] = L"Niepoprawna",
                   [L"ENG"] = L"Invalid",},

    [L"是否需要退出系统?"] = {
                   [L"CHN"] = L"是否需要退出系统?",
                   [L"POL"] = L"Napewno zamknac system?",
                   [L"ENG"] = L"Sure To ExitFrom System?",},

    [L"输入值的格式不正确! "] = {
                   [L"CHN"] = L"输入值的格式不正确! ",
                   [L"POL"] = L"Blad wprowadzania!",
                   [L"ENG"] = L"Input Error!",},

    [L"2.G55 工件偏置"] = {
                   [L"CHN"] = L"2.G55 工件偏置",
                   [L"POL"] = L"2.Odsuniecie G55",
                   [L"ENG"] = L"2.G55 Offset",},

    [L"当前状态不能执行微调功能!"] = {
                   [L"CHN"] = L"当前状态不能执行微调功能!",
                   [L"POL"] = L"Niedopuszcalne dzialanie w tym stanie!",
                   [L"ENG"] = L"Unable to   jiggle in   current sta-te!",},

    [L"文件为空文件! "] = {
                   [L"CHN"] = L"文件为空文件! ",
                   [L"POL"] = L"Plik jest pusty!",
                   [L"ENG"] = L"The file's empty!",},

    [L"11. 参考圆半径"] = {
                   [L"CHN"] = L"11. 参考圆半径",
                   [L"POL"] = L"11Promien Okregu Wzorcowego",
                   [L"ENG"] = L"11Ref Cir Radius",},

    [L"请设置当前刀具号"] = {
                   [L"CHN"] = L"请设置当前刀具号",
                   [L"POL"] = L"Ustaw aktualny nr narz.",
                   [L"ENG"] = L"Set Curre-nt Tool No.",},

    [L"现在回机械原点!"] = {
                   [L"CHN"] = L"现在回机械原点!",
                   [L"POL"] = L"Powr. do punktu zerowego?",
                   [L"ENG"] = L"Back to REF.point?",},

    [L"18. 刀补参数"] = {
                   [L"CHN"] = L"18. 刀补参数",
                   [L"POL"] = L"18.Komp. Narz.",
                   [L"ENG"] = L"18.Tool Comp",},

    [L"2.时间间隔  "] = {
                   [L"CHN"] = L"2.时间间隔  ",
                   [L"POL"] = L"2.Odstep czasu",
                   [L"ENG"] = L"2.Time Interval",},

    [L"下刀深度"] = {
                   [L"CHN"] = L"下刀深度",
                   [L"POL"] = L"Glebokosc kazdej warstwy",
                   [L"ENG"] = L"EachDpth",},

    [L"3.循环加工次数"] = {
                   [L"CHN"] = L"3.循环加工次数",
                   [L"POL"] = L"3.Ilosc Cykli",
                   [L"ENG"] = L"3.Cycle Times",},

    [L"* 首点作为零点"] = {
                   [L"CHN"] = L"* 首点作为零点",
                   [L"POL"] = L"*Pierwszy Punkt jako Zero",
                   [L"ENG"] = L"*1st PointAs Zero",},

    [L"1.回原点速度"] = {
                   [L"CHN"] = L"1.回原点速度",
                   [L"POL"] = L"1.Predkosc bazowania",
                   [L"ENG"] = L"1.REFP Speed",},

    [L"|M|Nc Studio 启动"] = {
                   [L"CHN"] = L"|M|Nc Studio 启动",
                   [L"POL"] = L"|M|Uruchomienie Nc Studio",
                   [L"ENG"] = L"|M|Nc Studio startup",},

    [L"8.屏蔽F 指令"] = {
                   [L"CHN"] = L"8.屏蔽F 指令",
                   [L"POL"] = L"8.Ignoruj kod F",
                   [L"ENG"] = L"8.Ignore F Code",},

    [L"1.全部回原点"] = {
                   [L"CHN"] = L"1.全部回原点",
                   [L"POL"] = L"1.Wszystkie bazuj",
                   [L"ENG"] = L"1.All Home",},

    [L"4.深孔加工方式"] = {
                   [L"CHN"] = L"4.深孔加工方式",
                   [L"POL"] = L"4.Tryb gleb. otw.",
                   [L"ENG"] = L"4.Deep Hole Mode",},

    [L"1.暂停时停主轴"] = {
                   [L"CHN"] = L"1.暂停时停主轴",
                   [L"POL"] = L"1.Wylaczone Wrzeciona w Pauzie",
                   [L"ENG"] = L"1.SOff at Pause",},

    [L"  ①存②取③删"] = {
                   [L"CHN"] = L"  ①存②取③删",
                   [L"POL"] = L"①Save②LD③Del",
                   [L"ENG"] = L"①Save②LD③Del",},

    [L"换刀后是否自动对刀"] = {
                   [L"CHN"] = L"换刀后是否自动对刀",
                   [L"POL"] = L"Kalibracja Narzedzia po Zmianie",
                   [L"ENG"] = L"Calibrate Tool Aft Change",},

    [L"14.Plt文件参数"] = {
                   [L"CHN"] = L"14.Plt文件参数",
                   [L"POL"] = L"14.Parametry Plt",
                   [L"ENG"] = L"14.Plt Params",},

    [L"* 加工深度"] = {
                   [L"CHN"] = L"* 加工深度",
                   [L"POL"] = L"* Glebokosc przetwarzania",
                   [L"ENG"] = L"* Process Depth",},

    [L"是否进行X 轴坐标清零？"] = {
                   [L"CHN"] = L"是否进行X 轴坐标清零？",
                   [L"POL"] = L"Clear X       coordinate?",
                   [L"ENG"] = L"Clear X       coordinate?",},

    [L"文件名:%s"] = {
                   [L"CHN"] = L"文件名:%s",
                   [L"POL"] = L"Plik:%s",
                   [L"ENG"] = L"Filename:%s",},

    [L"搜索起点坐标..."] = {
                   [L"CHN"] = L"搜索起点坐标...",
                   [L"POL"] = L"Searching Start Position",
                   [L"ENG"] = L"Searching Start Position",},

    [L"解析器忙"] = {
                   [L"CHN"] = L"解析器忙",
                   [L"POL"] = L"Interpreter przetwarza!",
                   [L"ENG"] = L"Parser is   busy!",},

    [L"Z 轴最大速度"] = {
                   [L"CHN"] = L"Z 轴最大速度",
                   [L"POL"] = L"Maks.Prekdosc Z",
                   [L"ENG"] = L"Max.Speed Of Z Axis",},

    [L"7.短线段限速有效"] = {
                   [L"CHN"] = L"7.短线段限速有效",
                   [L"POL"] = L"7.Limit Predkosc Krotkich Odcinkow",
                   [L"ENG"] = L"7.ShortSegSpdLmt",},

    [L"补偿使能"] = {
                   [L"CHN"] = L"补偿使能",
                   [L"POL"] = L"  Wlaczyc Kompensacje?",
                   [L"ENG"] = L"  Enable  Compensation?",},

    [L"请输入厂商密码"] = {
                   [L"CHN"] = L"请输入厂商密码",
                   [L"POL"] = L"Input manufactu-rer password:!",
                   [L"ENG"] = L"Input manufactu-rer password:!",},

    [L"10.Z向下刀速度"] = {
                   [L"CHN"] = L"10.Z向下刀速度",
                   [L"POL"] = L"10Predkosc Zaglebiania Z",
                   [L"ENG"] = L"10Z PlungeCutSpd",},

    [L"上次文件较大，是否需要加载？"] = {
                   [L"CHN"] = L"上次文件较大，是否需要加载？",
                   [L"POL"] = L"Ostatni plik jest duzy,OK aby wczytac?",
                   [L"ENG"] = L"Last file islarge,OK to load it?",},

    [L"U:  ①载②删③拷"] = {
                   [L"CHN"] = L"U:  ①载②删③拷",
                   [L"POL"] = L"U:①Wc②Us③Kp",
                   [L"ENG"] = L"U:①Ld②De③Copy",},

    [L"导入参数文件失败!"] = {
                   [L"CHN"] = L"导入参数文件失败!",
                   [L"POL"] = L"  Importowanie nieudane!",
                   [L"ENG"] = L" Import     Failed!",},

    [L"对刀行程保护!"] = {
                   [L"CHN"] = L"对刀行程保护!",
                   [L"POL"] = L"Alarm skoku narzedzia",
                   [L"ENG"] = L"Tool stroke alarm",},

    [L"1.系统信息"] = {
                   [L"CHN"] = L"1.系统信息",
                   [L"POL"] = L"1.Inform System",
                   [L"ENG"] = L"1.System Info",},

    [L"19. 转角容差"] = {
                   [L"CHN"] = L"19. 转角容差",
                   [L"POL"] = L"19Corner Toler",
                   [L"ENG"] = L"19Corner Toler",},

    [L"转角容差"] = {
                   [L"CHN"] = L"转角容差",
                   [L"POL"] = L"Corner Tolerance",
                   [L"ENG"] = L"Corner Tolerance",},

    [L"2.机床行程下限"] = {
                   [L"CHN"] = L"2.机床行程下限",
                   [L"POL"] = L"2.Dolny limit skoku",
                   [L"ENG"] = L"2.StrkLowerLmt",},

    [L"5.厂商参数"] = {
                   [L"CHN"] = L"5.厂商参数",
                   [L"POL"] = L"5.Param. Prod.",
                   [L"ENG"] = L"5.Mfr Param",},

    [L"未找到U盘!"] = {
                   [L"CHN"] = L"未找到U盘!",
                   [L"POL"] = L"No U-disk isfound!",
                   [L"ENG"] = L"No U-disk isfound!",},

    [L"列间距"] = {
                   [L"CHN"] = L"列间距",
                   [L"POL"] = L"Odstep KOlumn",
                   [L"ENG"] = L"ColSpace",},

    [L"OK: 加载      0:在本地和U 盘间切换\n注：文件夹不支持载入，删除，拷贝操作"] = {
                   [L"CHN"] = L"OK: 加载      0:在本地和U 盘间切换\n注：文件夹不支持载入，删除，拷贝操作",
                   [L"POL"] = L"OK:Load       0:Switch between U-disk and Local\nNOTICE:Folder does not\nsupport load, delete,copy\noperation",
                   [L"ENG"] = L"OK:Load       0:Switch between U-disk and Local\nNOTICE:Folder does not\nsupport load, delete,copy\noperation",},

    [L"* 循环加工次数"] = {
                   [L"CHN"] = L"* 循环加工次数",
                   [L"POL"] = L"* Liczba Cykli",
                   [L"ENG"] = L"* Cycle   Process Times",},

    [L"参考圆半径"] = {
                   [L"CHN"] = L"参考圆半径",
                   [L"POL"] = L"Promien okregu wzorcowego",
                   [L"ENG"] = L"Reference Circle Radius",},

    [L"2.停止时停主轴"] = {
                   [L"CHN"] = L"2.停止时停主轴",
                   [L"POL"] = L"2.Wyl. Wrzec. przy Zatrzym.",
                   [L"ENG"] = L"2.SOff at Stop",},

    [L"加工结束后亮红灯进行提示"] = {
                   [L"CHN"] = L"加工结束后亮红灯进行提示",
                   [L"POL"] = L"Czerwona lampa po przetwarzaniu",
                   [L"ENG"] = L"Red lamp  after process",},

    [L"1. X轴回退距离"] = {
                   [L"CHN"] = L"1. X轴回退距离",
                   [L"POL"] = L"1.Odl. Odsuniecia X",
                   [L"ENG"] = L"1.X Retract Dist",},

    [L"文件有错! "] = {
                   [L"CHN"] = L"文件有错! ",
                   [L"POL"] = L"Problem z plikiem",
                   [L"ENG"] = L"There's problem with the file",},

    [L"2.停车位置 "] = {
                   [L"CHN"] = L"2.停车位置 ",
                   [L"POL"] = L"2.Miejsce parkowania",
                   [L"ENG"] = L"2.Park Site",},

    [L"开启自动润滑"] = {
                   [L"CHN"] = L"开启自动润滑",
                   [L"POL"] = L"Otworz Autom. Smarowanie",
                   [L"ENG"] = L"Open Auto Lubrication",},

    [L"获取按键类型出错!"] = {
                   [L"CHN"] = L"获取按键类型出错!",
                   [L"POL"] = L"Get key type faild",
                   [L"ENG"] = L"Get key type faild",},

    [L"3.刀具偏置"] = {
                   [L"CHN"] = L"3.刀具偏置",
                   [L"POL"] = L"3.Odsuniecie Narz.",
                   [L"ENG"] = L"3.Tool Offset",},

    [L"参考圆速度"] = {
                   [L"CHN"] = L"参考圆速度",
                   [L"POL"] = L"Predkosc dla Okr. Wzorc.",
                   [L"ENG"] = L"Reference Circle Speed",},

    [L"换刀后是否回换刀前位置"] = {
                   [L"CHN"] = L"换刀后是否回换刀前位置",
                   [L"POL"] = L"Powrot do Pocz. Poz. Po wymianie",
                   [L"ENG"] = L"Back to Pre_Pos Aft Change",},

    [L"%d. 刀具%d"] = {
                   [L"CHN"] = L"%d. 刀具%d",
                   [L"POL"] = L"%d.Narz%d",
                   [L"ENG"] = L"%d.Tool%d",},

    [L"* 使用公制尺寸"] = {
                   [L"CHN"] = L"* 使用公制尺寸",
                   [L"POL"] = L"* Zaadoptuj uklad metryczny",
                   [L"ENG"] = L"* Adopt   Metric Size",},

    [L"7.阵列加工"] = {
                   [L"CHN"] = L"7.阵列加工",
                   [L"POL"] = L"7.Przetwarzanie szyku",
                   [L"ENG"] = L"7.Array Process",},

    [L"C:  ①载②删③拷"] = {
                   [L"CHN"] = L"C:  ①载②删③拷",
                   [L"POL"] = L"K:①Wc②Us③Kop",
                   [L"ENG"] = L"C:①Ld②De③Copy",},

    [L"3.加工前回原点"] = {
                   [L"CHN"] = L"3.加工前回原点",
                   [L"POL"] = L"3.Powrot do p. zer.",
                   [L"ENG"] = L"3.Back REF First",},

    [L"端口配置文件格式有错!"] = {
                   [L"CHN"] = L"端口配置文件格式有错!",
                   [L"POL"] = L"Problem jest z formatem pliku konfiguracyjnego!",
                   [L"ENG"] = L"There is a problem with the format of port configuration file!",},

    [L"写配置文件失败！"] = {
                   [L"CHN"] = L"写配置文件失败！",
                   [L"POL"] = L"NIeudana aktualizacja pliku konfig!",
                   [L"ENG"] = L"Failed to   Update Conf-ig File!",},
                   
    [L"当前按下的按键"] = {
                   [L"CHN"] = L"当前按下的按键",
                   [L"POL"] = L"Aktualny Klawisz",
                   [L"ENG"] = L"Current Key",},

    [L"确认开始微调?"] = {
                   [L"CHN"] = L"确认开始微调?",
                   [L"POL"] = L"OK to uruchomienia jig?",
                   [L"ENG"] = L"OK to start jiggle?",},

    [L"* 刀库容量"] = {
                   [L"CHN"] = L"* 刀库容量",
                   [L"POL"] = L"* Poj. magazynka",
                   [L"ENG"] = L"* Tool Ma-gazine Capacity",},

    [L"确认保存工件原点？"] = {
                   [L"CHN"] = L"确认保存工件原点？",
                   [L"POL"] = L"Sure to save origin?",
                   [L"ENG"] = L"Sure to save origin?",},

    [L"无刀具, 请检查"] = {
                   [L"CHN"] = L"无刀具, 请检查",
                   [L"POL"] = L"Brak narzedzia, prosze sprawdz!",
                   [L"ENG"] = L"No tool, plz check!",},

    [L"1.G54 工件偏置"] = {
                   [L"CHN"] = L"1.G54 工件偏置",
                   [L"POL"] = L"1.Odsuniecie G54",
                   [L"ENG"] = L"1.G54 Offset",},

    [L"APLU校验出错!"] = {
                   [L"CHN"] = L"APLU校验出错!",
                   [L"POL"] = L"Blad APLU crc!",
                   [L"ENG"] = L"APLU crc error!",},

    [L"是否进行Z 轴坐标清零？"] = {
                   [L"CHN"] = L"是否进行Z 轴坐标清零？",
                   [L"POL"] = L"Clear Z       coordinate?",
                   [L"ENG"] = L"Clear Z       coordinate?",},

    [L"时间: "] = {
                   [L"CHN"] = L"时间: ",
                   [L"POL"] = L"Czas:",
                   [L"ENG"] = L"Time:",},

    [L"文件删除失败!"] = {
                   [L"CHN"] = L"文件删除失败!",
                   [L"POL"] = L"Nieudana proba usuniecia pliku!",
                   [L"ENG"] = L"Failed To   Delete File!",},

    [L"1.选择语言"] = {
                   [L"CHN"] = L"1.选择语言",
                   [L"POL"] = L"1.Jezyk",
                   [L"ENG"] = L"1.Language",},

    [L"加工文件中存在程序名,请先手工删除！"] = {
                   [L"CHN"] = L"加工文件中存在程序名,请先手工删除！",
                   [L"POL"] = L"Znaleziono nazwe programu w pliku. Usun ja.!",
                   [L"ENG"] = L"Program namefound in thefile. Pleaseremove it!",},

    [L"单位：s"] = {
                   [L"CHN"] = L"单位：s",
                   [L"POL"] = L"Jednostka :s",
                   [L"ENG"] = L"Unit :s",},

    [L"未加载文件"] = {
                   [L"CHN"] = L"未加载文件",
                   [L"POL"] = L"Plik nie zostal wczytany!",
                   [L"ENG"] = L"No file     loaded!",},

    [L"初始化按键出错!"] = {
                   [L"CHN"] = L"初始化按键出错!",
                   [L"POL"] = L"Init key faild",
                   [L"ENG"] = L"Init key faild",},
                   
		[L"|E|非法操作！"] = {
                   [L"CHN"] = L"|E|非法操作！",
                   [L"POL"] = L"|E|Illegal Operation",
                   [L"ENG"] = L"|E|Illegal Operation",},	
                   
		[L"系统处于紧停状态, 不能启动主轴!"] = {
                   [L"CHN"] = L"系统处于紧停状态, 不能启动主轴!",
                   [L"POL"] = L"Spindle can't be started while system is under E-stop state!",
                   [L"ENG"] = L"Spindle can't be started while system is under E-stop state!",},	
                                      
		[L"|E|当前系统状态禁止启动主轴!"] = {
                   [L"CHN"] = L"|E|当前系统状态禁止启动主轴!",
                   [L"POL"] = L"|E|No start Spindle in current state!",
                   [L"ENG"] = L"|E|No start Spindle in current state!",},	
                                      
		[L"正在加工，真的停止主轴吗？"] = {
                   [L"CHN"] = L"正在加工，真的停止主轴吗？",
                   [L"POL"] = L"It's machining now! Do you really intend to stop the spindle?",
                   [L"ENG"] = L"It's machining now! Do you really intend to stop the spindle?",},	
                                      
		[L"X轴机械零点信号"] = {
                   [L"CHN"] = L"X轴机械零点信号",
                   [L"POL"] = L"X ORG",
                   [L"ENG"] = L"X ORG",},

		[L"X轴正向限位"] = {
                   [L"CHN"] = L"X轴正向限位",
                   [L"POL"] = L"Limit +X",
                   [L"ENG"] = L"X Limit+",},

		[L"X轴负向限位"] = {
                   [L"CHN"] = L"X轴负向限位",
                   [L"POL"] = L"Limit -X",
                   [L"ENG"] = L"X Limit-",},

		[L"Y轴机械零点信号"] = {
                   [L"CHN"] = L"Y轴机械零点信号",
                   [L"POL"] = L"Y ORG",
                   [L"ENG"] = L"Y ORG",},

		[L"Y轴正向限位"] = {
                   [L"CHN"] = L"Y轴正向限位",
                   [L"POL"] = L"Limit +Y",
                   [L"ENG"] = L"Y Limit+",},

		[L"Y轴负向限位"] = {
                   [L"CHN"] = L"Y轴负向限位",
                   [L"POL"] = L"Limit -Y",
                   [L"ENG"] = L"Y Limit-",},

		[L"Z轴机械零点信号"] = {
                   [L"CHN"] = L"Z轴机械零点信号",
                   [L"POL"] = L"Z ORG",
                   [L"ENG"] = L"Z ORG",},

		[L"Z轴正向限位"] = {
                   [L"CHN"] = L"Z轴正向限位",
                   [L"POL"] = L"Limit +Z",
                   [L"ENG"] = L"Z Limit+",},

		[L"Z轴负向限位"] = {
                   [L"CHN"] = L"Z轴负向限位",
                   [L"POL"] = L"Limit -Z",
                   [L"ENG"] = L"Z Limit-",},

		[L"程序开始"] = {
                   [L"CHN"] = L"程序开始",
                   [L"POL"] = L"Start",
                   [L"ENG"] = L"Start",},

		[L"端口输入GX10"] = {
                   [L"CHN"] = L"端口输入GX10",
                   [L"POL"] = L"GX10",
                   [L"ENG"] = L"GX10",},
		[L"程序停止"] = {
                   [L"CHN"] = L"程序停止",
                   [L"POL"] = L"stop",
                   [L"ENG"] = L"stop",},

		[L"端口输入GX11"] = {
                   [L"CHN"] = L"端口输入GX11",
                   [L"POL"] = L"GX11",
                   [L"ENG"] = L"GX11",},

		[L"对刀行程保护"] = {
                   [L"CHN"] = L"对刀行程保护",
                   [L"POL"] = L"OCHR_KALNARZ",
                   [L"ENG"] = L"CALCUTTER_PROTECT",},

		[L"端口输入GX12"] = {
                   [L"CHN"] = L"端口输入GX12",
                   [L"POL"] = L"GX12",
                   [L"ENG"] = L"GX12",},

		[L"程序暂停"] = {
                   [L"CHN"] = L"程序暂停",
                   [L"POL"] = L"pauza",
                   [L"ENG"] = L"pause",},

		[L"端口输入GX13"] = {
                   [L"CHN"] = L"端口输入GX13",
                   [L"POL"] = L"GX13",
                   [L"ENG"] = L"GX13",},

		[L"端口输入GX14"] = {
                   [L"CHN"] = L"端口输入GX14",
                   [L"POL"] = L"GX14",
                   [L"ENG"] = L"GX14",},

		[L"紧停"] = {
                   [L"CHN"] = L"紧停",
                   [L"POL"] = L"Estop",
                   [L"ENG"] = L"Estop",},

		[L"Z轴对刀信号"] = {
                   [L"CHN"] = L"Z轴对刀信号",
                   [L"POL"] = L"Kalibr Narz",
                   [L"ENG"] = L"Tool Cali",},

		[L"LCD"] = {
                   [L"CHN"] = L"LCD",
                   [L"POL"] = L"LCD",
                   [L"ENG"] = L"LCD",},

		[L"主轴反向"] = {
                   [L"CHN"] = L"主轴反向",
                   [L"POL"] = L"Obrot",
                   [L"ENG"] = L"Spin Rev",},

		[L"主轴启动"] = {
                   [L"CHN"] = L"主轴启动",
                   [L"POL"] = L"Obr wl.",
                   [L"ENG"] = L"Spin On",},

		[L"主轴转速档位2输出端口"] = {
                   [L"CHN"] = L"主轴转速档位2输出端口",
                   [L"POL"] = L"S_2",
                   [L"ENG"] = L"S_2",},

		[L"主轴转速档位1输出端口"] = {
                   [L"CHN"] = L"主轴转速档位1输出端口",
                   [L"POL"] = L"S_1",
                   [L"ENG"] = L"S_1",},

		[L"主轴转速档位0输出端口"] = {
                   [L"CHN"] = L"主轴转速档位0输出端口",
                   [L"POL"] = L"S_0",
                   [L"ENG"] = L"S_0",},

		[L"黄灯"] = {
                   [L"CHN"] = L"黄灯",
                   [L"POL"] = L"Zolta dioda",
                   [L"ENG"] = L"Yellow LED",},

		[L"工件冷却"] = {
                   [L"CHN"] = L"工件冷却",
                   [L"POL"] = L"Chlodziwo",
                   [L"ENG"] = L"Workpiece Cool",},

		[L"绿灯"] = {
                   [L"CHN"] = L"绿灯",
                   [L"POL"] = L"Zielona dioda",
                   [L"ENG"] = L"Green Led",},

		[L"主轴冷却"] = {
                   [L"CHN"] = L"主轴冷却",
                   [L"POL"] = L"Obrot",
                   [L"ENG"] = L"Spin Cool",},

		[L"红灯"] = {
                   [L"CHN"] = L"红灯",
                   [L"POL"] = L"Czerwona dioda",
                   [L"ENG"] = L"Red Led",},

		[L"自动加润滑油"] = {
                   [L"CHN"] = L"自动加润滑油",
                   [L"POL"] = L"Autom. Smar.",
                   [L"ENG"] = L"Auto Oil",},

		[L"液晶屏复位"] = {
                   [L"CHN"] = L"液晶屏复位",
                   [L"POL"] = L"Reset LCD",
                   [L"ENG"] = L"LCD Reset",},

		[L"松刀确认信号"] = {
                   [L"CHN"] = L"松刀确认信号",
                   [L"POL"] = L"Spindle unclamping tool detection",
                   [L"ENG"] = L"Spindle unclamping tool detection",},

		[L"夹刀确认信号"] = {
                   [L"CHN"] = L"夹刀确认信号",
                   [L"POL"] = L"Spindle clamping tool detection",
                   [L"ENG"] = L"Spindle clamping tool detection",},

		[L"松夹刀"] = {
                   [L"CHN"] = L"松夹刀",
                   [L"POL"] = L"clamp/uclamp tool",
                   [L"ENG"] = L"clamp/uclamp tool",},

		[L"紧停按钮"] = {
                   [L"CHN"] = L"紧停按钮",
                   [L"POL"] = L"ESTOP2",
                   [L"ENG"] = L"ESTOP2",},
                   
		[L"RUN_LED"] = {
                   [L"CHN"] = L"RUN_LED",
                   [L"POL"] = L"RUN_LED",
                   [L"ENG"] = L"RUN_LED",},
                   
		[L"SPIN_LED"] = {
                   [L"CHN"] = L"SPIN_LED",
                   [L"POL"] = L"SPIN_LED",
                   [L"ENG"] = L"SPIN_LED",},
                   
		[L"ALM_LED"] = {
                   [L"CHN"] = L"ALM_LED",
                   [L"POL"] = L"ALM_LED",
                   [L"ENG"] = L"ALM_LED",},
                   
		[L"GY18_LED"] = {
                   [L"CHN"] = L"GY18_LED",
                   [L"POL"] = L"GY18_LED",
                   [L"ENG"] = L"GY18_LED",},
                   
		[L"GY19_LED"] = {
                   [L"CHN"] = L"GY19_LED",
                   [L"POL"] = L"GY19_LED",
                   [L"ENG"] = L"GY19_LED",},
                   
		[L"GY20_LED"] = {
                   [L"CHN"] = L"GY20_LED",
                   [L"POL"] = L"GY20_LED",
                   [L"ENG"] = L"GY20_LED",},
                   
		[L"Shift+0:回固定点"] = {
                   [L"CHN"] = L"Shift+0:回固定点",
                   [L"POL"] = L"Shift+0:back  to fixed point",
                   [L"ENG"] = L"Shift+0:back  to fixed point",},
                      
		[L"Shift+2:第一次对刀"] = {
                   [L"CHN"] = L"Shift+2:第一次对刀",
                   [L"POL"] = L"Shift+2:      Kalibr.       Narzedzia 1",
                   [L"ENG"] = L"Shift+2:Calib-rate cutter   first",},
                      
		[L"Shift+3:第二次对刀"] = {
                   [L"CHN"] = L"Shift+3:第二次对刀",
                   [L"POL"] = L"Shift+3:      Kalibr.       Narzedzia 2",
                   [L"ENG"] = L"Shift+3:Calib-rate cutter   second",},

                      
		[L"Shift+.:主轴档位减小"] = {
                   [L"CHN"] = L"Shift+.:主轴档位减小",
                   [L"POL"] = L"Shift+.:      zmniejsz bieg wrzeciona",
                   [L"ENG"] = L"Shift+.:      decrease      spindle gears",},

                      
		[L"Shift+-:主轴档位增加"] = {
                   [L"CHN"] = L"Shift+-:主轴档位增加",
                   [L"POL"] = L"Shift+-:      zwiekszenie   biegu         wrzeciona",
                   [L"ENG"] = L"Shift+-:      increase      spindle gears",},
                      
		[L"Shift+7:回机械原点"] = {
                   [L"CHN"] = L"Shift+7:回机械原点",
                   [L"POL"] = L"Shift+7:      powrot do     punktu        zerowego",                                      
                   [L"ENG"] = L"Shift+7: back to reference  point",},
                      
		[L"Shift+8:工件坐标与机械坐标的显示切换"] = {
                   [L"CHN"] = L"Shift+8:工件坐标与机械坐标的显示切换",
                   [L"POL"] = L"Shift+8:      przelaczenie  wyswietlania  WCS i MCS",                                      
                   [L"ENG"] = L"Shift+8:switchbetween WCS   display and   MCS display",},
                      
		[L"Shift+9:对刀"] = {
                   [L"CHN"] = L"Shift+9:对刀",
                   [L"POL"] = L"Shift+9:      kalibr. narz.",                                      
                   [L"ENG"] = L"Shift+9: tool calibration",},
                      
		[L"Shift+XY=0:X轴坐标清零"] = {
                   [L"CHN"] = L"Shift+XY=0:X轴坐标清零",
                   [L"POL"] = L"Shift+XY=0:   zeruj wsp. X",                                      
                   [L"ENG"] = L"Shift+XY=0:   clear X       coordinate",},
                      
		[L"Shift+Z=0: Y轴坐标清零"] = {
                   [L"CHN"] = L"Shift+Z=0: Y轴坐标清零",
                   [L"POL"] = L"Shift+Z=0:    zeruj wsp. Y",                                      
                   [L"ENG"] = L"Shift+Z=0:    clear Y       coordinate",},
                        
		[L"Shift+菜单: 显示帮助信息"] = {
                   [L"CHN"] = L"Shift+菜单: 显示帮助信息",
                   [L"POL"] = L"Shift+Menu:   wyswietl pomoc",                                      
                   [L"ENG"] = L"Shift+Menu:   display help  info",},
                      
		[L"Shift+暂停: 暂停微调"] = {
                   [L"CHN"] = L"Shift+暂停: 暂停微调",
                   [L"POL"] = L"Shift+Pause:  pause jiggle",
                   [L"ENG"] = L"Shift+Pause:  pause jiggle",},
                      
		[L"Shift+开始：断点继续"] = {
                   [L"CHN"] = L"Shift+开始：断点继续",
                   [L"POL"] = L"Shift+Start:  przywrocenie\npunktu przerw.",                   
                   [L"ENG"] = L"Shift+Start:  breakpoint    resuming",},
                      
		[L"Shift+1:主轴档位减小"] = {
                   [L"CHN"] = L"Shift+1:主轴档位减小",
                   [L"POL"] = L"Shift+1:      zmniejsz      bieg wrzeciona",                   
                   [L"ENG"] = L"Shift+1:      decrease      spindle gears",},
                      
		[L"Shift+7:主轴档位增加"] = {
                   [L"CHN"] = L"Shift+7:主轴档位增加",
                   [L"POL"] = L"Shift+7:      zwiekszenie   biegu         wrzeciona",
                   [L"ENG"] = L"Shift+7:      increase      spindle gears",},
                                            
		[L"Shift+4:回机械原点"] = {
                   [L"CHN"] = L"Shift+4:回机械原点",
                   [L"POL"] = L"Shift+4:      powrot do p.  zerowego",                                      
                   [L"ENG"] = L"Shift+4: back to reference  point",},
                      
		[L"Shift+5:回工件原点"] = {
                   [L"CHN"] = L"Shift+5:回工件原点",
                   [L"POL"] = L"Shift+5:      powrot do p.  zerowegop.    obr.",                                      
                   [L"ENG"] = L"Shift+5: back to original   point",},
                      
		[L"Shift+0:对刀"] = {
                   [L"CHN"] = L"Shift+0:对刀",
                   [L"POL"] = L"Shift+0:      kalibr. narz.",                                      
                   [L"ENG"] = L"Shift+0:tool  calibration",},
                    
                      
		[L"Shift+6:测量刀具长度"] = {
                   [L"CHN"] = L"Shift+6:测量刀具长度",
                   [L"POL"] = L"Shift+6:Auto  ustawienie    dlugosci narz.",                                      
                   [L"ENG"] = L"Shift+6:Auto  set tool      length",},
                      
		[L"Shift+9:手动松夹刀"] = {
                   [L"CHN"] = L"Shift+9:手动松夹刀",
                   [L"POL"] = L"Shift+9:      Spin-dle tool ON or OFF",
                   [L"ENG"] = L"Shift+9:      Spin-dle tool ON or OFF",},
                      
		[L"Shift+XY=0:Z轴坐标清零"] = {
                   [L"CHN"] = L"Shift+XY=0:Z轴坐标清零",
                   [L"POL"] = L"Shift+XY=0:   zeruj wsp. Z",
                   [L"ENG"] = L"Shift+XY=0:   clear Z       coordinate",},
                      
		[L"Shift+1:手动松夹刀"] = {
                   [L"CHN"] = L"Shift+1:手动松夹刀",
                   [L"POL"] = L"Shift+1:      Spin-dle tool ON or OFF",
                   [L"ENG"] = L"Shift+1:      Spin-dle tool ON or OFF",},
                                                                     
		[L"缩写："] = {
                   [L"CHN"] = L"缩写：",
                   [L"POL"] = L"Abbreviation: REF.:Referencepoint         SOff:Spindle  Off           LmitRls.:LimitRelease",
                   [L"ENG"] = L"Abbreviation: REF.:Referencepoint         SOff:Spindle  Off           LmitRls.:LimitRelease",},                                                                                                                                       	
}
}
function GetLanguageString()
	lua_table = ResTable["strTable"][StringKey()]
	if lua_table == nil then
		return L"NoTable"
	else
		lua_string = lua_table[LanguageKey()]
		if lua_string == nil then
			return L"NoString"
		else
			return lua_string
		end
	end
end

function GetLanguageTotal()
	lang_table = ResTable["langTable"]
	langInfo_table = ResTable["langInfoTable"]
	count = 0
	if lang_table then
		for i,v in pairs(lang_table) do
			count = count + 1
			AddName(v)
			AddInfo(langInfo_table[v])
		end
	end
	return count
end

function GetModuleName()
	return ResTable["szModule"]
end

function GetVersion()
	return ResTable["nVersion"] 
end
